// AUTOGENERATED by tools/gen_openapi_ts.py from loop_implementation/api/openapi.yaml.
// Do not edit by hand. Run `uv run python tools/gen_openapi_ts.py` to refresh.

/* Component schemas */

export interface APIKey {
  created_at?: string;
  id?: string;
  key_prefix?: string;
  last_used_at?: string | null;
  name?: string;
  revoked_at?: string | null;
  scopes?: string[];
}

export interface APIKeyCreated {
  id?: string;
  key?: string;
  name?: string;
  scopes?: string[];
}

export interface Agent {
  active_version?: number | null;
  created_at?: string;
  description?: string;
  id?: string;
  name?: string;
  slug?: string;
  workspace_id?: string;
}

export interface AgentCreate {
  description?: string;
  name: string;
  slug: string;
}

export interface AgentResponse {
  content?: ContentPart[];
  conversation_id?: string;
  end_turn?: boolean;
  suggested_actions?: Record<string, unknown>[];
}

export interface AgentVersion {
  agent_id?: string;
  deploy_state?: "inactive" | "canary" | "active" | "rolled_back";
  deployed_at?: string | null;
  eval_status?: "pending" | "running" | "passed" | "failed" | "skipped";
  id?: string;
  version?: number;
}

export interface AuditLogEntry {
  action?: string;
  actor_user_id?: string | null;
  after_state?: Record<string, unknown> | null;
  before_state?: Record<string, unknown> | null;
  client_ip?: string;
  created_at?: string;
  id?: string;
  request_id?: string;
  resource_id?: string | null;
  resource_type?: string;
  user_agent?: string | null;
}

export interface Budget {
  created_at?: string;
  hard_usd?: number | null;
  id?: string;
  remaining_usd?: number | null;
  scope?: "workspace" | "agent" | "conversation" | "day";
  scope_id?: string | null;
  soft_usd?: number | null;
  spent_usd?: number;
}

export interface ContentPart {
  bytes_b64?: string;
  mime_type?: string;
  text?: string;
  type: "text" | "image" | "audio" | "file";
  url?: string;
}

export interface Conversation {
  agent_id?: string;
  channel_type?: string;
  id?: string;
  last_at?: string;
  status?: "active" | "idle" | "closed" | "escalated";
  user_id?: string;
}

export type ConversationDetail = Conversation & { "turns"?: Turn[] };

export interface EvalCase {
  expected: Record<string, unknown>;
  input: Record<string, unknown>;
  name: string;
  scorers: { "config"?: Record<string, unknown>; "kind"?: "llm_judge" | "embedding_sim" | "regex_match" | "json_schema" | "tool_call_assert" | "latency_le" | "cost_le" | "hallucination" | "toxicity" | "pii_leak" }[];
}

export interface EvalRun {
  agent_version_id?: string;
  ended_at?: string | null;
  id?: string;
  started_at?: string;
  status?: string;
  suite_id?: string;
}

export type EvalRunDetail = EvalRun & { "results"?: { "case_name"?: string; "passed"?: boolean; "regressed"?: boolean; "score"?: number }[] };

export interface EvalSuite {
  case_count?: number;
  id?: string;
  name?: string;
}

export interface InvokeRequest {
  channel: "web" | "whatsapp" | "slack" | "teams" | "telegram" | "sms" | "email" | "discord" | "voice" | "webhook";
  content: ContentPart[];
  conversation_id: string;
  metadata?: Record<string, unknown>;
  user_id: string;
}

export interface KB {
  embedding_model?: string;
  id?: string;
  name?: string;
  vector_dim?: number;
}

export interface KBCreate {
  embedding_model?: string;
  name: string;
  vector_dim?: number;
}

export interface KBIngestNotion {
  integration_token: string;
  page_or_db: string;
  type: string;
}

export interface KBIngestS3 {
  s3_uri: string;
  type: string;
}

export interface KBIngestUrl {
  crawl?: boolean;
  type: string;
  url: string;
}

export interface MCPServer {
  id?: string;
  install_status?: "pending" | "installed" | "failed" | "disabled";
  manifest?: { "tools"?: { "description"?: string; "input_schema"?: Record<string, unknown>; "name"?: string }[] };
  name?: string;
  source_url?: string;
  version?: string;
}

export interface ProblemDetail {
  detail?: string;
  instance?: string;
  request_id?: string;
  status: number;
  title: string;
  type: string;
}

export type RegionName = "na-east" | "eu-west";

export interface RetrievalChunk {
  byte_range?: number[];
  chunk_id?: string;
  content?: string;
  doc_id?: string;
  score?: number;
  source_uri?: string;
}

export interface SecretRef {
  agent_version_id?: string;
  created_at?: string;
  id?: string;
  rotated_at?: string | null;
  secret_name?: string;
}

export interface Trace {
  spans?: { "attrs"?: Record<string, unknown>; "cost_usd"?: number; "kind"?: "llm" | "tool" | "retrieval" | "memory" | "channel"; "latency_ms"?: number; "name"?: string; "parent_span_id"?: string | null; "span_id"?: string; "started_at"?: string; "status"?: string }[];
  turn_id?: string;
}

export interface Turn {
  content_json?: Record<string, unknown>;
  cost_usd?: number;
  ended_at?: string;
  id?: string;
  latency_ms?: number;
  role?: string;
  seq?: number;
  started_at?: string;
  token_in?: number;
  token_out?: number;
}

export interface UsageReport {
  from?: string;
  rows?: { "agent_seconds"?: number; "compute_usd"?: number; "date"?: string; "dim"?: string; "llm_input_tokens"?: number; "llm_output_tokens"?: number; "llm_usd"?: number; "tool_usd"?: number }[];
  to?: string;
}

export interface Version {
  api_version?: string;
  build_hash?: string;
  built_at?: string;
}

export interface WebhookRegistration {
  created_at?: string;
  events?: string[];
  id?: string;
  is_active?: boolean;
  last_triggered_at?: string | null;
  url?: string;
}

export interface Workspace {
  created_at?: string;
  id?: string;
  name?: string;
  plan?: "hobby" | "pro" | "team" | "enterprise";
  region?: RegionName;
  slug?: string;
}

export interface WorkspaceCreate {
  name: string;
  region?: RegionName;
  slug: string;
}

export interface WorkspaceMember {
  email?: string;
  full_name?: string;
  invited_at?: string;
  joined_at?: string | null;
  role?: "owner" | "admin" | "editor" | "operator" | "viewer";
  user_id?: string;
}

export interface WorkspacePatch {
  name?: string;
}

/* Operation map */

export interface Operations {
  GetAgents: {
    method: "GET";
    path: "/agents";
    request: unknown;
    response: Agent[];
  };
  PostAgents: {
    method: "POST";
    path: "/agents";
    request: AgentCreate;
    response: Agent;
  };
  GetAgentsByAgentId: {
    method: "GET";
    path: "/agents/{agent_id}";
    request: unknown;
    response: Agent;
  };
  DeleteAgentsByAgentId: {
    method: "DELETE";
    path: "/agents/{agent_id}";
    request: unknown;
    response: unknown;
  };
  GetAgentsByAgentIdConversations: {
    method: "GET";
    path: "/agents/{agent_id}/conversations";
    request: unknown;
    response: { "items"?: Conversation[]; "next_cursor"?: string | null };
  };
  PostAgentsByAgentIdInvoke: {
    method: "POST";
    path: "/agents/{agent_id}/invoke";
    request: InvokeRequest;
    response: AgentResponse;
  };
  PostAgentsByAgentIdVersions: {
    method: "POST";
    path: "/agents/{agent_id}/versions";
    request: unknown;
    response: AgentVersion;
  };
  GetAuditEvents: {
    method: "GET";
    path: "/audit-events";
    request: unknown;
    response: AuditLogEntry[];
  };
  GetBudgets: {
    method: "GET";
    path: "/budgets";
    request: unknown;
    response: Budget[];
  };
  PostBudgets: {
    method: "POST";
    path: "/budgets";
    request: { "hard_usd"?: number; "scope": "workspace" | "agent" | "conversation" | "day"; "scope_id"?: string | null; "soft_usd"?: number };
    response: Budget;
  };
  GetConversationsByConversationId: {
    method: "GET";
    path: "/conversations/{conversation_id}";
    request: unknown;
    response: ConversationDetail;
  };
  PostConversationsByConversationIdMessages: {
    method: "POST";
    path: "/conversations/{conversation_id}/messages";
    request: { "content": ContentPart[] };
    response: unknown;
  };
  PostConversationsByConversationIdTakeover: {
    method: "POST";
    path: "/conversations/{conversation_id}/takeover";
    request: { "reason": string };
    response: Conversation;
  };
  GetEvalRunsByRunId: {
    method: "GET";
    path: "/eval-runs/{run_id}";
    request: unknown;
    response: EvalRunDetail;
  };
  PostEvalSuites: {
    method: "POST";
    path: "/eval-suites";
    request: { "cases"?: EvalCase[]; "name": string };
    response: EvalSuite;
  };
  GetEvalSuitesBySuiteIdCases: {
    method: "GET";
    path: "/eval-suites/{suite_id}/cases";
    request: unknown;
    response: EvalCase[];
  };
  PostEvalSuitesBySuiteIdCases: {
    method: "POST";
    path: "/eval-suites/{suite_id}/cases";
    request: EvalCase;
    response: EvalCase;
  };
  DeleteEvalSuitesBySuiteIdCases: {
    method: "DELETE";
    path: "/eval-suites/{suite_id}/cases";
    request: unknown;
    response: unknown;
  };
  PostEvalSuitesBySuiteIdRuns: {
    method: "POST";
    path: "/eval-suites/{suite_id}/runs";
    request: { "agent_version_id": string; "baseline_version_id"?: string };
    response: EvalRun;
  };
  GetHealthz: {
    method: "GET";
    path: "/healthz";
    request: unknown;
    response: unknown;
  };
  PostKb: {
    method: "POST";
    path: "/kb";
    request: KBCreate;
    response: KB;
  };
  PostKbByKbIdIngest: {
    method: "POST";
    path: "/kb/{kb_id}/ingest";
    request: KBIngestUrl | KBIngestNotion | KBIngestS3;
    response: { "document_id"?: string; "status"?: string };
  };
  GetKbByKbIdSearch: {
    method: "GET";
    path: "/kb/{kb_id}/search";
    request: unknown;
    response: RetrievalChunk[];
  };
  GetMcp: {
    method: "GET";
    path: "/mcp";
    request: unknown;
    response: MCPServer[];
  };
  PostMcp: {
    method: "POST";
    path: "/mcp";
    request: { "config"?: Record<string, unknown>; "source": string };
    response: MCPServer;
  };
  GetReadyz: {
    method: "GET";
    path: "/readyz";
    request: unknown;
    response: unknown;
  };
  GetTracesSearch: {
    method: "GET";
    path: "/traces/search";
    request: unknown;
    response: { "items"?: Trace[]; "next_cursor"?: string | null };
  };
  GetTracesByTurnId: {
    method: "GET";
    path: "/traces/{turn_id}";
    request: unknown;
    response: Trace;
  };
  GetUsage: {
    method: "GET";
    path: "/usage";
    request: unknown;
    response: UsageReport;
  };
  GetVersion: {
    method: "GET";
    path: "/version";
    request: unknown;
    response: Version;
  };
  PostWebhooksIncoming: {
    method: "POST";
    path: "/webhooks/incoming";
    request: { "events": string[]; "secret"?: string; "url": string };
    response: WebhookRegistration;
  };
  GetWorkspaces: {
    method: "GET";
    path: "/workspaces";
    request: unknown;
    response: Workspace[];
  };
  PostWorkspaces: {
    method: "POST";
    path: "/workspaces";
    request: WorkspaceCreate;
    response: Workspace;
  };
  GetWorkspacesByWorkspaceId: {
    method: "GET";
    path: "/workspaces/{workspace_id}";
    request: unknown;
    response: Workspace;
  };
  PatchWorkspacesByWorkspaceId: {
    method: "PATCH";
    path: "/workspaces/{workspace_id}";
    request: WorkspacePatch;
    response: Workspace;
  };
  GetWorkspacesByWorkspaceIdApiKeys: {
    method: "GET";
    path: "/workspaces/{workspace_id}/api-keys";
    request: unknown;
    response: APIKey[];
  };
  PostWorkspacesByWorkspaceIdApiKeys: {
    method: "POST";
    path: "/workspaces/{workspace_id}/api-keys";
    request: { "name": string; "scopes": string[] };
    response: APIKeyCreated;
  };
  GetWorkspacesByWorkspaceIdMembers: {
    method: "GET";
    path: "/workspaces/{workspace_id}/members";
    request: unknown;
    response: WorkspaceMember[];
  };
  PostWorkspacesByWorkspaceIdMembers: {
    method: "POST";
    path: "/workspaces/{workspace_id}/members";
    request: { "email": string; "role": "owner" | "admin" | "editor" | "operator" | "viewer" };
    response: WorkspaceMember;
  };
  GetWorkspacesByWorkspaceIdSecrets: {
    method: "GET";
    path: "/workspaces/{workspace_id}/secrets";
    request: unknown;
    response: SecretRef[];
  };
}
