// AUTOGENERATED by tools/gen_ts_sdk.py from packages/sdk-py/loop/types.py.
// Do not edit by hand. Run `uv run python tools/gen_ts_sdk.py` to refresh.

export interface AgentEvent {
  workspace_id: string;
  conversation_id: string;
  user_id: string;
  channel: ChannelType;
  content: ContentPart[];
  metadata?: Record<string, unknown>;
  received_at: string;
}

export interface AgentResponse {
  conversation_id: string;
  content: ContentPart[];
  streaming?: boolean;
  suggested_actions?: Record<string, unknown>[];
  end_turn?: boolean;
}

export type ChannelType = "web" | "whatsapp" | "slack" | "teams" | "telegram" | "sms" | "email" | "discord" | "voice" | "webhook";

export interface ContentPart {
  type: "text" | "image" | "audio" | "file";
  text?: string | null;
  url?: string | null;
  mime_type?: string | null;
  bytes_b64?: string | null;
}

export interface Span {
  span_id: string;
  parent_span_id?: string | null;
  kind: "llm" | "tool" | "retrieval" | "memory" | "channel";
  name: string;
  started_at: string;
  ended_at?: string | null;
  latency_ms?: number;
  cost_usd?: number;
  status?: "ok" | "error" | "timeout";
  attrs?: Record<string, string>;
}

export interface ToolCall {
  name: string;
  server: string;
  args: Record<string, unknown>;
  result?: unknown | null;
  error?: string | null;
  latency_ms?: number;
  cost_usd?: number;
}

export interface Trace {
  turn_id: string;
  spans?: Span[];
  total_cost_usd?: number;
  total_latency_ms?: number;
  iteration_count?: number;
}

export interface Turn {
  turn_id?: string;
  workspace_id: string;
  conversation_id: string;
  agent_name: string;
  event: AgentEvent;
  response?: AgentResponse | null;
  status?: TurnStatus;
  trace?: Trace | null;
  started_at: string;
  ended_at?: string | null;
  cost_usd?: number;
  iteration_count?: number;
  degrade_reason?: string | null;
}

export interface TurnEvent {
  type: "token" | "tool_call" | "tool_call_start" | "tool_call_end" | "tool_result" | "retrieval" | "trace" | "degrade" | "complete";
  payload: Record<string, unknown>;
  ts: string;
}

export type TurnStatus = "pending" | "running" | "completed" | "degraded" | "failed";
