"""Smoke tests for the cp-api TS client generator (S152)."""

from __future__ import annotations

import importlib.util
import re
import sys
from pathlib import Path

import pytest

REPO_ROOT = Path(__file__).resolve().parent.parent
TOOL_PATH = REPO_ROOT / "tools" / "gen_cp_api_client.py"


def _load_tool():
    sys.path.insert(0, str(REPO_ROOT / "tools"))
    try:
        spec = importlib.util.spec_from_file_location(
            "gen_cp_api_client", TOOL_PATH
        )
        assert spec is not None and spec.loader is not None
        module = importlib.util.module_from_spec(spec)
        spec.loader.exec_module(module)
        return module
    finally:
        sys.path.pop(0)


def test_generator_emits_in_sync_output() -> None:
    tool = _load_tool()
    rendered = tool.render_ts()
    on_disk = tool.OUT_PATH.read_text(encoding="utf-8")
    assert rendered == on_disk, (
        "apps/studio/src/lib/cp-api/generated.ts is stale; "
        "run pnpm --filter @loop/studio run gen:cp-api"
    )


def test_generated_client_surface() -> None:
    tool = _load_tool()
    rendered = tool.render_ts()
    # Header + the three core exports the studio relies on.
    assert "AUTOGENERATED" in rendered
    assert "export interface CpApi {" in rendered
    assert "export function createCpApi" in rendered
    assert "export function createCpApiFetch" in rendered


def test_types_match_openapi_schemas() -> None:
    import yaml

    tool = _load_tool()
    rendered = tool.render_ts()
    data = yaml.safe_load(tool.OPENAPI_PATH.read_text(encoding="utf-8"))
    schemas = data.get("components", {}).get("schemas", {})
    if not schemas:
        pytest.skip("no component schemas defined")
    for name in schemas:
        # Each component schema becomes either an interface or a type alias.
        pattern = rf"^export (interface|type) {re.escape(name)}\b"
        assert re.search(pattern, rendered, re.MULTILINE), (
            f"missing emitted declaration for {name}"
        )
