"""Drift-detection guard for the auto-generated TS SDK.

The committed apps/studio/src/lib/sdk-types.ts file MUST match what
tools/gen_ts_sdk.py emits from the current Python source of truth.
If a developer adds / renames / re-types a public field in
packages/sdk-py/loop/types.py without re-running the generator,
this test fires.
"""

from __future__ import annotations

import importlib.util
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
GEN_PATH = REPO_ROOT / "tools" / "gen_ts_sdk.py"
TS_OUT_PATH = REPO_ROOT / "apps" / "studio" / "src" / "lib" / "sdk-types.ts"


def _load_gen():
    spec = importlib.util.spec_from_file_location("gen_ts_sdk", GEN_PATH)
    assert spec is not None and spec.loader is not None
    module = importlib.util.module_from_spec(spec)
    sys.modules["gen_ts_sdk"] = module
    spec.loader.exec_module(module)
    return module


def test_committed_ts_matches_generator() -> None:
    gen = _load_gen()
    rendered = gen.render_ts()
    committed = TS_OUT_PATH.read_text(encoding="utf-8")
    assert committed == rendered, (
        "TS SDK out of sync with packages/sdk-py/loop/types.py. "
        "Run `uv run python tools/gen_ts_sdk.py`."
    )


def test_check_mode_returns_zero_when_in_sync() -> None:
    gen = _load_gen()
    assert gen.main(["--check"]) == 0


def test_render_contains_each_public_symbol() -> None:
    gen = _load_gen()
    rendered = gen.render_ts()
    for name in ("ChannelType", "TurnStatus", "ContentPart", "Trace", "Turn"):
        assert f"{name}" in rendered


def test_check_mode_detects_drift(tmp_path: Path, monkeypatch) -> None:
    """If we point the generator at a temp file that has stale content,
    --check must exit non-zero."""
    gen = _load_gen()
    fake = tmp_path / "sdk-types.ts"
    fake.write_text("// stale\n", encoding="utf-8")
    monkeypatch.setattr(gen, "TS_OUT_PATH", fake)
    assert gen.main(["--check"]) == 1


def test_write_mode_creates_file(tmp_path: Path, monkeypatch) -> None:
    gen = _load_gen()
    fake = tmp_path / "out" / "sdk-types.ts"
    monkeypatch.setattr(gen, "TS_OUT_PATH", fake)
    assert gen.main([]) == 0
    body = fake.read_text(encoding="utf-8")
    assert body.startswith("// AUTOGENERATED")
    assert "ChannelType" in body
