"""Loop control-plane package: tenant identity, agents, deploys, audit.

Public surface (so far):

* `auth` -- token verifier abstractions + an HS256 dev impl.
* `workspaces` -- workspace + membership domain (in-memory store).
* `api_keys` -- API key issue / verify / revoke (plaintext returned once).
* `authorize` -- workspace-scope RBAC helper used by every facade.
* `workspace_api` -- HTTP-shaped facade over the workspace service.
* `api_keys_api` -- HTTP-shaped facade over the API-key service.
* `errors` -- canonical LOOP-API-* error mapper.
* `logging` -- structlog wiring + per-request log context.
"""

from loop_control_plane.api_keys import (
    ApiKey,
    ApiKeyError,
    ApiKeyService,
    IssuedApiKey,
)
from loop_control_plane.api_keys_api import ApiKeyAPI
from loop_control_plane.audit import (
    AuditContext,
    AuditEventInput,
    AuditLog,
    AuditLogEntry,
    AuditLogError,
    InMemoryAuditLog,
    audit_log_append,
)
from loop_control_plane.audit_coverage import (
    AUDIT_COVERAGE,
    WriteEndpointAuditCoverage,
    coverage_gaps,
    required_write_routes,
)
from loop_control_plane.auth import (
    AuthError,
    HS256Verifier,
    IdentityClaims,
    TokenVerifier,
    has_scope,
)
from loop_control_plane.authorize import (
    AuthorisationError,
    authorize_workspace_access,
    role_satisfies,
)
from loop_control_plane.billing import (
    BillingError,
    BillingService,
    InMemoryStripe,
    StripeClient,
    StripeCustomer,
    StripeInvoice,
    StripeUsageRecord,
)
from loop_control_plane.deploy import (
    BaselineRegistry,
    BuildResult,
    Deploy,
    DeployArtifact,
    DeployController,
    DeployError,
    DeployPhase,
    EvalGate,
    EvalReport,
    ImageBuilder,
    ImageRegistry,
    InMemoryBaselineRegistry,
    InMemoryEvalGate,
    InMemoryImageBuilder,
    InMemoryImageRegistry,
    InMemoryKubeClient,
    KubeClient,
)
from loop_control_plane.errors import (
    LoopApiError,
    map_to_loop_api_error,
)
from loop_control_plane.inbox import (
    InboxError,
    InboxItem,
    InboxQueue,
    InboxStatus,
)
from loop_control_plane.inbox_api import InboxAPI
from loop_control_plane.kms import (
    KMS,
    KMS_BACKENDS,
    InMemoryKMS,
    KMSError,
    build_kms_backend,
)
from loop_control_plane.mcp_marketplace import (
    CommunityPublishFlow,
    CommunityPublishResult,
    DuplicateReviewError,
    DuplicateVersionError,
    FirstPartyCatalog,
    InMemoryMarketplaceStore,
    InstalledToolView,
    InstallNotFoundError,
    ManifestSignatureVerifier,
    MarketplaceAcceptanceGate,
    MarketplaceAnalytics,
    MarketplaceBrowseItem,
    MarketplaceBrowser,
    MarketplaceError,
    MarketplaceInstall,
    MarketplaceInstaller,
    MarketplacePublisher,
    MarketplaceReview,
    MarketplaceReviews,
    MarketplaceServer,
    MarketplaceUsageAggregate,
    McpServerManifest,
    McpServerVersion,
    McpToolSpec,
    PublishClient,
    PublishResult,
    QualityBreakdown,
    QualityScorer,
    RejectedManifestError,
    ServerNotFoundError,
    ServerPublishCli,
    SigningKey,
    TrustedPublisherVerifier,
    UnknownVersionError,
    compute_manifest_digest,
    first_party_manifests,
)
from loop_control_plane.object_store import (
    OBJECT_STORE_BACKENDS,
    InMemoryObjectStore,
    ObjectStore,
    ObjectStoreError,
    build_object_store_backend,
)
from loop_control_plane.secrets import (
    SECRETS_BACKENDS,
    InMemorySecretsBackend,
    SecretAccess,
    SecretsBackend,
    SecretsBackendError,
    build_secrets_backend,
)
from loop_control_plane.usage import (
    DAY_MS,
    UsageEvent,
    UsageLedger,
    UsageRollup,
    aggregate,
)
from loop_control_plane.workspace_api import WorkspaceAPI
from loop_control_plane.workspaces import (
    Membership,
    Role,
    Workspace,
    WorkspaceError,
    WorkspaceService,
)

__all__ = [
    "AUDIT_COVERAGE",
    "DAY_MS",
    "KMS",
    "KMS_BACKENDS",
    "OBJECT_STORE_BACKENDS",
    "SECRETS_BACKENDS",
    "ApiKey",
    "ApiKeyAPI",
    "ApiKeyError",
    "ApiKeyService",
    "AuditContext",
    "AuditEventInput",
    "AuditLog",
    "AuditLogEntry",
    "AuditLogError",
    "AuthError",
    "AuthorisationError",
    "BaselineRegistry",
    "BillingError",
    "BillingService",
    "BuildResult",
    "CommunityPublishFlow",
    "CommunityPublishResult",
    "Deploy",
    "DeployArtifact",
    "DeployController",
    "DeployError",
    "DeployPhase",
    "DuplicateReviewError",
    "DuplicateVersionError",
    "EvalGate",
    "EvalReport",
    "FirstPartyCatalog",
    "HS256Verifier",
    "IdentityClaims",
    "ImageBuilder",
    "ImageRegistry",
    "InMemoryAuditLog",
    "InMemoryBaselineRegistry",
    "InMemoryEvalGate",
    "InMemoryImageBuilder",
    "InMemoryImageRegistry",
    "InMemoryKMS",
    "InMemoryKubeClient",
    "InMemoryMarketplaceStore",
    "InMemoryObjectStore",
    "InMemorySecretsBackend",
    "InMemoryStripe",
    "InboxAPI",
    "InboxError",
    "InboxItem",
    "InboxQueue",
    "InboxStatus",
    "InstallNotFoundError",
    "InstalledToolView",
    "IssuedApiKey",
    "KMSError",
    "KubeClient",
    "LoopApiError",
    "ManifestSignatureVerifier",
    "MarketplaceAcceptanceGate",
    "MarketplaceAnalytics",
    "MarketplaceBrowseItem",
    "MarketplaceBrowser",
    "MarketplaceError",
    "MarketplaceInstall",
    "MarketplaceInstaller",
    "MarketplacePublisher",
    "MarketplaceReview",
    "MarketplaceReviews",
    "MarketplaceServer",
    "MarketplaceUsageAggregate",
    "McpServerManifest",
    "McpServerVersion",
    "McpToolSpec",
    "Membership",
    "ObjectStore",
    "ObjectStoreError",
    "PublishClient",
    "PublishResult",
    "QualityBreakdown",
    "QualityScorer",
    "RejectedManifestError",
    "Role",
    "SecretAccess",
    "SecretsBackend",
    "SecretsBackendError",
    "ServerNotFoundError",
    "ServerPublishCli",
    "SigningKey",
    "StripeClient",
    "StripeCustomer",
    "StripeInvoice",
    "StripeUsageRecord",
    "TokenVerifier",
    "TrustedPublisherVerifier",
    "UnknownVersionError",
    "UsageEvent",
    "UsageLedger",
    "UsageRollup",
    "Workspace",
    "WorkspaceAPI",
    "WorkspaceError",
    "WorkspaceService",
    "WriteEndpointAuditCoverage",
    "aggregate",
    "audit_log_append",
    "authorize_workspace_access",
    "build_kms_backend",
    "build_object_store_backend",
    "build_secrets_backend",
    "compute_manifest_digest",
    "coverage_gaps",
    "first_party_manifests",
    "has_scope",
    "map_to_loop_api_error",
    "required_write_routes",
    "role_satisfies",
]
