"""SLSA Level-3 build-provenance verification for container images — S802.

Every container image built by Loop CI must carry a valid SLSA Level-3
provenance attestation before it can be deployed. The deploy gate rejects
images that are missing provenance or whose provenance fails verification.

Background
----------
SLSA (Supply-chain Levels for Software Artifacts, https://slsa.dev) defines
four levels of build integrity.  Level 3 requires:

* Provenance is generated by the build system (not the developer).
* Provenance is non-falsifiable: the builder identity is backed by a
  short-lived OIDC certificate (e.g. GitHub Actions / Workload Identity).
* Build is isolated — no direct developer access during the build.

In Loop CI this is achieved with ``slsa-github-generator`` (for GHA) or
``buildah + cosign`` with Fulcio-issued OIDC certificates. The resulting
attestation is attached to the image digest in OCI-artifact form and
surfaced by ``cosign verify-attestation --type slsa_provenance``.

This module provides the *policy seam* — it is not the verifier itself
(cosign is), but it defines the data model, the Protocol that the deploy
controller calls, and the in-memory stubs used by tests.

Data model
----------
:class:`SlsaProvenance` mirrors the SLSA v0.2 provenance predicate fields
that Loop policy cares about:

* ``subject_digest``  — ``sha256:...`` of the image the provenance covers.
* ``builder_id``      — e.g. ``https://github.com/slsa-framework/slsa-github-generator/.github/workflows/generator_container_slsa3.yml@refs/tags/v1.9.0``
* ``build_type``      — SLSA build type URI.
* ``materials``       — list of ``{"uri": ..., "digest": {...}}`` dicts (source VCS ref).
* ``metadata``        — arbitrary predicate metadata dict (optional).

Verification policy
-------------------
:class:`ProvenancePolicy` holds the set of *trusted builder IDs*.  The
production policy accepts the ``slsa-github-generator`` builder reachable
at ``https://github.com/slsa-framework/slsa-github-generator/...``.

Fakes for testing
-----------------
:class:`InMemoryProvenanceStore` lets tests register provenance objects by
image digest.  :class:`StubProvenanceVerifier` uses the store to simulate
``cosign verify-attestation`` without forking a process.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any, Protocol

__all__ = [
    "InMemoryProvenanceStore",
    "ProvenanceError",
    "ProvenancePolicy",
    "ProvenanceVerifier",
    "SlsaProvenance",
    "StubProvenanceVerifier",
]

# ---------------------------------------------------------------------------
# Error
# ---------------------------------------------------------------------------


class ProvenanceError(ValueError):
    """Raised when provenance is missing, invalid, or untrusted."""


# ---------------------------------------------------------------------------
# Data model
# ---------------------------------------------------------------------------


@dataclass(frozen=True, slots=True)
class SlsaProvenance:
    """SLSA v0.2 provenance predicate attached to a container image.

    Args:
        subject_digest: ``sha256:<hex>`` of the OCI image the provenance
            covers. Must match the ``BuildResult.digest`` the deploy
            controller recorded.
        builder_id: URI identifying the SLSA builder that produced the
            image (e.g. the ``slsa-github-generator`` reusable workflow ref).
        build_type: SLSA build-type URI (e.g.
            ``https://slsa.dev/provenance/v0.2``).
        materials: List of SLSA ``materials`` entries.  Each entry is a
            ``{"uri": str, "digest": {"sha1": str | "sha256": str}}`` dict.
        metadata: Arbitrary predicate metadata; preserved but not validated
            by this module.
    """

    subject_digest: str
    builder_id: str
    build_type: str
    materials: list[dict[str, Any]] = field(default_factory=list)
    metadata: dict[str, Any] = field(default_factory=dict)


# ---------------------------------------------------------------------------
# Policy
# ---------------------------------------------------------------------------


@dataclass(frozen=True, slots=True)
class ProvenancePolicy:
    """Describes which SLSA builders are trusted.

    The production policy trusts only the ``slsa-github-generator``
    container workflow and the Loop internal Tekton builder.  Tests
    typically pass ``trusted_builder_ids={"test-builder"}`` for simplicity.

    Args:
        trusted_builder_ids: Frozenset of trusted builder ID URI prefixes.
            Matching is done with ``builder_id.startswith(prefix)`` so that
            pinned ``@refs/...`` suffixes are still covered by a prefix match.
    """

    trusted_builder_ids: frozenset[str] = field(
        default_factory=lambda: frozenset(
            {
                "https://github.com/slsa-framework/slsa-github-generator/",
                "https://tekton.loop.internal/",
            }
        )
    )

    def is_trusted_builder(self, builder_id: str) -> bool:
        return any(builder_id.startswith(prefix) for prefix in self.trusted_builder_ids)


# ---------------------------------------------------------------------------
# Protocol
# ---------------------------------------------------------------------------


class ProvenanceVerifier(Protocol):
    """Seam for the provenance verification step in the deploy gate.

    ``verify`` is called with the image digest (``sha256:<hex>``) after the
    image has been built but *before* it is pushed to the registry.  It must
    return the verified :class:`SlsaProvenance` on success or raise
    :class:`ProvenanceError` if provenance is absent, cannot be decoded, or
    does not satisfy the policy.
    """

    def verify(self, image_digest: str, policy: ProvenancePolicy) -> SlsaProvenance:
        """Return verified provenance for *image_digest*.

        Raises:
            ProvenanceError: Provenance is missing or policy is not satisfied.
        """
        ...


# ---------------------------------------------------------------------------
# In-memory store (used by StubProvenanceVerifier)
# ---------------------------------------------------------------------------


class InMemoryProvenanceStore:
    """Register test provenance objects keyed by image digest.

    Usage::

        store = InMemoryProvenanceStore()
        store.register(SlsaProvenance(subject_digest="sha256:abc", ...))
        verifier = StubProvenanceVerifier(store)
    """

    def __init__(self) -> None:
        self._by_digest: dict[str, SlsaProvenance] = {}

    def register(self, provenance: SlsaProvenance) -> None:
        self._by_digest[provenance.subject_digest] = provenance

    def get(self, image_digest: str) -> SlsaProvenance | None:
        return self._by_digest.get(image_digest)


# ---------------------------------------------------------------------------
# Stub verifier for unit / integration tests
# ---------------------------------------------------------------------------


class StubProvenanceVerifier:
    """Test double for :class:`ProvenanceVerifier`.

    Backed by :class:`InMemoryProvenanceStore`.  Raises
    :class:`ProvenanceError` if the digest is not registered or the builder
    is untrusted according to *policy*.
    """

    def __init__(self, store: InMemoryProvenanceStore) -> None:
        self._store = store

    def verify(self, image_digest: str, policy: ProvenancePolicy) -> SlsaProvenance:
        prov = self._store.get(image_digest)
        if prov is None:
            raise ProvenanceError(
                f"no SLSA provenance found for image digest {image_digest!r}; "
                "deploy rejected (SLSA Level-3 gate)"
            )
        if not policy.is_trusted_builder(prov.builder_id):
            raise ProvenanceError(
                f"builder {prov.builder_id!r} is not in the trusted builder set; "
                "deploy rejected (SLSA Level-3 gate)"
            )
        return prov
