// AUTOGENERATED by tools/gen_cp_api_client.py from
// loop_implementation/api/openapi.yaml. Do not edit by hand.
// Run `pnpm --filter @loop/studio run gen:cp-api` to refresh.

/* Component schemas */

export interface APIKey {
  created_at?: string;
  id?: string;
  key_prefix?: string;
  last_used_at?: string | null;
  name?: string;
  revoked_at?: string | null;
  scopes?: string[];
}

export interface APIKeyCreated {
  id?: string;
  key?: string;
  name?: string;
  scopes?: string[];
}

export interface AdversarialReview {
  actionId: string;
  bullets: ReviewBullet[];
}

export interface Agent {
  active_version?: number | null;
  created_at?: string;
  description?: string;
  id?: string;
  name?: string;
  slug?: string;
  workspace_id?: string;
}

export interface AgentCreate {
  description?: string;
  name: string;
  slug: string;
}

export interface AgentList {
  items: Agent[];
}

export interface AgentResponse {
  content?: ContentPart[];
  conversation_id?: string;
  end_turn?: boolean;
  suggested_actions?: Record<string, unknown>[];
}

export interface AgentTool {
  description: string;
  id: string;
  kind: "mcp" | "http";
  name: string;
  source: string;
}

export interface AgentToolList {
  items: AgentTool[];
}

export interface AgentVersion {
  agent_id: string;
  created_at: string;
  created_by: string;
  id: string;
  notes: string;
  spec: Record<string, unknown>;
  version: number;
  workspace_id: string;
}

export interface AgentVersionCreate {
  notes?: string;
  spec?: Record<string, unknown>;
}

export interface AgentVersionList {
  items: AgentVersion[];
}

export interface AuditEvent {
  action?: string;
  actor_sub?: string;
  id?: string;
  occurred_at?: string;
  outcome?: "success" | "denied" | "error";
  payload_hash?: string | null;
  request_id?: string | null;
  resource_id?: string | null;
  resource_type?: string;
  workspace_id?: string;
}

export interface AuditEventList {
  items: AuditEvent[];
  total: number;
}

export interface AuditLogEntry {
  action?: string;
  actor_user_id?: string | null;
  after_state?: Record<string, unknown> | null;
  before_state?: Record<string, unknown> | null;
  client_ip?: string;
  created_at?: string;
  id?: string;
  request_id?: string;
  resource_id?: string | null;
  resource_type?: string;
  user_agent?: string | null;
}

export interface AuthExchangeRequest {
  id_token: string;
}

export interface AuthExchangeResponse {
  access_expires_at_ms: number;
  access_token: string;
  refresh_expires_at_ms: number;
  refresh_token: string;
  token_type: "Bearer";
}

export interface Budget {
  created_at?: string;
  hard_usd?: number | null;
  id?: string;
  remaining_usd?: number | null;
  scope?: "workspace" | "agent" | "conversation" | "day";
  scope_id?: string | null;
  soft_usd?: number | null;
  spent_usd?: number;
}

export interface CanaryStage {
  durationMinutes: number;
  guardrails: string[];
  id: string;
  percent: number;
  status: "pending" | "in_progress" | "passed" | "halted";
}

export interface CoBuilderAction {
  cost: CoBuilderCost;
  diff: CoBuilderDiffHunk;
  evidenceRef: string;
  id: string;
  mode: "suggest" | "edit" | "drive";
  provenance: CoBuilderProvenance[];
  rationale: string;
  requiredScopes: string[];
  title: string;
}

export interface CoBuilderCost {
  latencyMs: number;
  usd: number;
}

export interface CoBuilderDiffHunk {
  body: string;
  path: string;
}

export interface CoBuilderProvenance {
  evidenceRef: string;
  excerpt: string;
  source: string;
}

export interface CoBuilderWorkspace {
  actions: CoBuilderAction[];
  agentId: string | null;
  agentName: string;
  operator: OperatorContext;
  review: AdversarialReview;
  rubberDuck: RubberDuckDiagnosis;
  workspaceId: string;
}

export interface ConductorData {
  agentId: string;
  agentName: string;
  branch: string;
  contracts: HandoffContract[];
  degradedReason?: string;
  delegations: DelegationTrace[];
  objectState: "draft" | "saved" | "staged" | "canary" | "production" | "archived";
  orchestrationEvidence: string;
  permissionReason?: string;
  subAgents: ConductorSubAgent[];
  topology: ConductorTopologyEdge[];
  trust: "healthy" | "watching" | "drifting" | "degraded" | "blocked";
}

export interface ConductorSubAgent {
  activeHandoffs: number;
  budgetUsd: number;
  costEvidence: string;
  currentOwner: string;
  evalConfidence: "high" | "medium" | "low" | "unsupported";
  evalCoveragePercent: number;
  failurePaths: string[];
  id: string;
  latencyEvidence: string;
  latencyP95Ms: number;
  memoryAccess: string;
  name: string;
  objectState: "draft" | "saved" | "staged" | "canary" | "production" | "archived";
  owner: string;
  purpose: string;
  spentUsd: number;
  status: "ready" | "active" | "degraded" | "blocked";
  tools: ConductorToolGrant[];
  traceSpans: string[];
  trust: "healthy" | "watching" | "drifting" | "degraded" | "blocked";
  version: string;
}

export interface ConductorToolGrant {
  evidence: string;
  mode: "read" | "draft" | "live" | "blocked";
  name: string;
}

export interface ConductorTopologyEdge {
  id: string;
  label: string;
  source: string;
  state: "ready" | "active" | "violated" | "blocked";
  target: string;
}

export interface ContentPart {
  bytes_b64?: string;
  mime_type?: string;
  text?: string;
  type: "text" | "image" | "audio" | "file";
  url?: string;
}

export interface Conversation {
  agent_id: string;
  created_at: string;
  id: string;
  last_message_at: string;
  message_count: number;
  operator_taken_over: boolean;
  state: "open" | "closed" | "in-takeover";
  subject: string;
  workspace_id: string;
}

export interface ConversationDetail {
  last_assistant_message: string;
  last_user_message: string;
  messages: ConversationMessage[];
  metadata: Record<string, unknown>;
  summary: Conversation;
}

export interface ConversationMessage {
  body: string;
  conversation_id: string;
  created_at: string;
  id: string;
  role: "user" | "assistant" | "operator" | "system";
}

export interface CutoverPlan {
  id: string;
  rollbackTriggers: RollbackTrigger[];
  shadow: ShadowTrafficSummary;
  stages: CanaryStage[];
}

export interface DelegationTrace {
  contractId: string;
  costUsd: number;
  evidence: string;
  id: string;
  latencyMs: number;
  sourceAgent: string;
  spanId: string;
  status: "ok" | "warning" | "failed";
  targetAgent: string;
  traceId: string;
}

export interface DiffEntry {
  delta?: string;
  evidenceRef: string;
  id: string;
  mode: "structure" | "behavior" | "cost" | "risk";
  severity: "ok" | "advisory" | "blocking";
  sourcePath: string;
  summary: string;
  targetPath: string;
}

export interface EvalCase {
  attachments?: string[];
  created_at?: string;
  created_by?: string;
  expected: Record<string, unknown>;
  id?: string;
  input: Record<string, unknown>;
  name: string;
  scorers: { "config"?: Record<string, unknown>; "kind"?: "llm_judge" | "embedding_sim" | "regex_match" | "json_schema" | "tool_call_assert" | "latency_le" | "cost_le" | "hallucination" | "toxicity" | "pii_leak" }[];
  source?: string;
  source_ref?: string;
  suite_id?: string;
  workspace_id?: string;
}

export interface EvalCaseList {
  items: EvalCase[];
}

export interface EvalRun {
  agent_version_id?: string;
  ended_at?: string | null;
  id?: string;
  started_at?: string;
  status?: string;
  suite_id?: string;
}

export type EvalRunDetail = EvalRun & { "results"?: { "case_name"?: string; "passed"?: boolean; "regressed"?: boolean; "score"?: number }[] };

export interface EvalSuite {
  case_count?: number;
  id?: string;
  name?: string;
}

export interface HandoffContract {
  budgetUsd: number;
  currentOwner: string;
  evidenceTrace: string;
  fallback: string;
  from: string;
  id: string;
  inputSchema: string[];
  memoryAccess: string;
  name: string;
  outputSchema: string[];
  purpose: string;
  state: "ready" | "active" | "violated" | "blocked";
  timeoutMs: number;
  to: string;
  toolGrants: string[];
  violation?: string;
}

export interface ImportLineage {
  archive: string;
  archiveSha: string;
  importId: string;
  importedAt: string;
  source: string;
  steps: LineageStep[];
}

export type InboxChannel = "web" | "voice" | "sms" | "whatsapp" | "slack";

export interface InboxClaimRequest {
  now_ms?: number;
  operator_id?: string | null;
}

export interface InboxEscalateRequest {
  agent_id: string;
  conversation_id: string;
  last_message_excerpt?: string;
  now_ms?: number;
  reason: string;
  user_id: string;
}

export interface InboxItem {
  agent_id: string;
  channel?: InboxChannel;
  claimed_at_ms: number | null;
  conversation_id: string;
  created_at_ms: number;
  id: string;
  last_message_excerpt: string;
  operator_id: string | null;
  reason: string;
  resolved_at_ms: number | null;
  status: InboxStatus;
  team_id?: string;
  user_id: string;
  workspace_id: string;
}

export interface InboxItemList {
  items: InboxItem[];
}

export interface InboxResolveRequest {
  now_ms?: number;
}

export type InboxStatus = "pending" | "claimed" | "resolved";

export interface InvokeRequest {
  channel: "web" | "whatsapp" | "slack" | "teams" | "telegram" | "sms" | "email" | "discord" | "voice" | "webhook";
  content: ContentPart[];
  conversation_id: string;
  metadata?: Record<string, unknown>;
  user_id: string;
}

export interface KB {
  embedding_model?: string;
  id?: string;
  name?: string;
  vector_dim?: number;
}

export interface KBCreate {
  embedding_model?: string;
  name: string;
  vector_dim?: number;
}

export interface KBIngestNotion {
  integration_token: string;
  page_or_db: string;
  type: string;
}

export interface KBIngestS3 {
  s3_uri: string;
  type: string;
}

export interface KBIngestUrl {
  crawl?: boolean;
  type: string;
  url: string;
}

export interface LineageStep {
  detail: string;
  evidenceRef: string;
  id: string;
  label: string;
  status: "ok" | "warn" | "error";
}

export interface MCPServer {
  id?: string;
  install_status?: "pending" | "installed" | "failed" | "disabled";
  manifest?: { "tools"?: { "description"?: string; "input_schema"?: Record<string, unknown>; "name"?: string }[] };
  name?: string;
  source_url?: string;
  version?: string;
}

export interface MarketplaceBrowseItem {
  average_rating: number;
  calls: number;
  categories: string[];
  description: string;
  install_button_enabled: boolean;
  installs: number;
  latest_version: string;
  name: string;
  publisher: string;
  quality_score: number;
  server_id: string;
  slug: string;
}

export interface MarketplaceBrowseList {
  items: MarketplaceBrowseItem[];
}

export interface MemoryStudioEntry {
  after: string;
  agent_id: string;
  before: string;
  confidence: "high" | "medium" | "low" | "unsupported";
  deletion_reason: string;
  deletion_state: "available" | "blocked" | "queued";
  id: string;
  key: string;
  replay_impact: string;
  retention_policy: string;
  safety_flags: "none" | "pii" | "secret-like" | "conflict" | "stale" | "weak-evidence"[];
  scope: "user" | "bot" | "session";
  source: string;
  source_trace: string;
  updated_at: string;
  user_id?: string | null;
  workspace_id: string;
  writer_version: string;
}

export interface MemoryStudioEntryList {
  items: MemoryStudioEntry[];
}

export interface MigrationParityWorkspace {
  cutover: CutoverPlan;
  diffs: DiffEntry[];
  lineage: ImportLineage;
  readiness: ParityReadiness;
  repairs: RepairSuggestion[];
  replay: ParityReplayCase[];
}

export interface OperatorContext {
  budgetRemainingUsd: number;
  maxMode: "suggest" | "edit" | "drive";
  scopes: string[];
}

export interface OperatorMessageRequest {
  body: string;
}

export interface ParityReadiness {
  advisoryCount: number;
  blockingCount: number;
  overallScore: number;
  parityPassing: number;
  parityTotal: number;
}

export interface ParityReplayCase {
  evidenceRef: string;
  expectedTarget: string;
  id: string;
  observedTarget: string;
  status: "pass" | "regress" | "improve" | "skipped";
  transcript: string;
}

export interface ProblemDetail {
  detail?: string;
  instance?: string;
  request_id?: string;
  status: number;
  title: string;
  type: string;
}

export type RegionName = "na-east" | "eu-west";

export interface RepairSuggestion {
  confidence: "low" | "medium" | "high";
  diffId: string;
  groundingRef: string;
  id: string;
  patchSummary: string;
  rationale: string;
}

export interface ResolutionEvalCaseRequest {
  attachments: string[];
  expectedOutcome: string;
  failureReason: string;
  id: string;
  linkedTrace: string;
  source: "operator-resolution";
  title: string;
}

export interface ResolutionEvalCaseResponse {
  case: EvalCase;
  case_id: string;
  ok: boolean;
  suite_id: string;
}

export interface RetrievalChunk {
  byte_range?: number[];
  chunk_id?: string;
  content?: string;
  doc_id?: string;
  score?: number;
  source_uri?: string;
}

export interface ReviewBullet {
  body: string;
  evidenceRef: string;
  id: string;
  severity: "info" | "warn" | "block";
}

export interface RollbackTrigger {
  action: string;
  evidenceRef: string;
  id: string;
  metric: "regression" | "error_rate" | "cost_spike" | "manual";
  threshold: string;
}

export interface RubberDuckDiagnosis {
  caseId: string;
  failureSummary: string;
  findings: RubberDuckFinding[];
  proposedFix: CoBuilderAction;
}

export interface RubberDuckFinding {
  evidenceRef: string;
  observation: string;
  step: string;
}

export interface RuntimeTurnRequest {
  agent_name?: string;
  budget?: TurnBudget;
  channel?: "web" | "whatsapp" | "slack" | "teams" | "telegram" | "sms" | "email" | "discord" | "voice" | "webhook";
  content?: ContentPart[];
  conversation_id: string;
  input?: string | null;
  metadata?: Record<string, unknown>;
  model?: string | null;
  received_at?: string | null;
  request_id?: string | null;
  system_prompt?: string;
  user_id: string;
  workspace_id: string;
}

export interface RuntimeTurnResponse {
  events: TurnEvent[];
  reply: { "text": string };
  turn_id: string;
}

export interface SecretRef {
  agent_version_id?: string;
  created_at?: string;
  id?: string;
  rotated_at?: string | null;
  secret_name?: string;
}

export interface ShadowTrafficSummary {
  agreement: number;
  costPerTurnDelta: string;
  divergences: number;
  durationMinutes: number;
  evidenceRef: string;
  turns: number;
}

export interface Trace {
  spans?: { "attrs"?: Record<string, unknown>; "cost_usd"?: number; "kind"?: "llm" | "tool" | "retrieval" | "memory" | "channel"; "latency_ms"?: number; "name"?: string; "parent_span_id"?: string | null; "span_id"?: string; "started_at"?: string; "status"?: string }[];
  turn_id?: string;
}

export interface Turn {
  content_json?: Record<string, unknown>;
  cost_usd?: number;
  ended_at?: string;
  id?: string;
  latency_ms?: number;
  role?: string;
  seq?: number;
  started_at?: string;
  token_in?: number;
  token_out?: number;
}

export interface TurnBudget {
  fallback_model?: string | null;
  max_cost_usd?: number;
  max_iterations?: number;
  max_output_tokens_per_iter?: number;
  max_runtime_seconds?: number;
}

export interface TurnEvent {
  payload: Record<string, unknown>;
  ts: string;
  type: "token" | "tool_call" | "tool_call_start" | "tool_call_end" | "tool_result" | "retrieval" | "trace" | "degrade" | "complete";
}

export interface UsageReport {
  from?: string;
  rows?: { "agent_seconds"?: number; "compute_usd"?: number; "date"?: string; "dim"?: string; "llm_input_tokens"?: number; "llm_output_tokens"?: number; "llm_usd"?: number; "tool_usd"?: number }[];
  to?: string;
}

export interface Version {
  api_version?: string;
  build_hash?: string;
  built_at?: string;
}

export interface VoiceConfig {
  asr_provider: "deepgram" | "whisper" | "google";
  numbers: VoiceNumber[];
  tts_provider: "elevenlabs" | "openai" | "polly";
  workspace_id: string;
}

export interface VoiceConfigPatch {
  asr_provider?: "deepgram" | "whisper" | "google";
  tts_provider?: "elevenlabs" | "openai" | "polly";
}

export interface VoiceDemoLink {
  audited: boolean;
  expiresIn: string;
  id: string;
  label: string;
  scope: string;
}

export interface VoiceEvalCase {
  coverage: string;
  evidenceRef: string;
  id: string;
  name: string;
  passRate: number;
}

export interface VoiceLatencySpan {
  budgetMs: number;
  id: string;
  label: string;
  ms: number;
  status: "ok" | "watch" | "over";
}

export interface VoiceNumber {
  e164: string;
  id: string;
  label: string;
  provisioned_at_ms: number;
  region: string;
}

export interface VoiceStageConfig {
  asr: string;
  bargeIn: boolean;
  phoneNumber: string;
  tts: string;
  voice: string;
}

export interface VoiceStageModel {
  agentName: string;
  callState: "dev" | "staging" | "production";
  config: VoiceStageConfig;
  demoLinks: VoiceDemoLink[];
  evals: VoiceEvalCase[];
  queuedSpeech: string;
  spans: VoiceLatencySpan[];
  transcript: VoiceTranscriptTurn[];
  waveform: number[];
}

export interface VoiceTranscriptTurn {
  id: string;
  speaker: "caller" | "agent" | "tool";
  text: string;
  timestamp: string;
}

export interface WebhookRegistration {
  created_at?: string;
  events?: string[];
  id?: string;
  is_active?: boolean;
  last_triggered_at?: string | null;
  url?: string;
}

export interface Workspace {
  created_at?: string;
  id?: string;
  name?: string;
  plan?: "hobby" | "pro" | "team" | "enterprise";
  region?: RegionName;
  role?: "owner" | "admin" | "member" | "viewer";
  slug?: string;
}

export interface WorkspaceCreate {
  name: string;
  region?: RegionName;
  slug: string;
}

export interface WorkspaceList {
  items: Workspace[];
  page: number;
  page_size: number;
  total: number;
}

export interface WorkspaceMember {
  email?: string;
  full_name?: string;
  invited_at?: string;
  joined_at?: string | null;
  role?: "owner" | "admin" | "editor" | "operator" | "viewer";
  user_id?: string;
}

export interface WorkspacePatch {
  name?: string;
}


/**
 * Minimal fetch wrapper used by the generated cp-api client.
 *
 * Studio code rarely calls this directly; instead it imports
 * ``CpApi`` below and the wrapper handles URL templating, JSON
 * serialisation, and bearer auth.
 */
export interface CpApiClientOptions {
  baseUrl: string;
  token?: string;
  fetch?: typeof fetch;
}

export type CpApiFetch = <T>(
  method: string,
  path: string,
  body?: unknown,
) => Promise<T>;

export function createCpApiFetch(opts: CpApiClientOptions): CpApiFetch {
  const f = opts.fetch ?? fetch;
  const base = opts.baseUrl.replace(/\/$/, "");
  return async <T>(method: string, path: string, body?: unknown): Promise<T> => {
    const headers: Record<string, string> = { accept: "application/json" };
    if (opts.token) headers.authorization = `Bearer ${opts.token}`;
    const init: RequestInit = { method, headers };
    if (body !== undefined) {
      headers["content-type"] = "application/json";
      init.body = JSON.stringify(body);
    }
    const response = await f(`${base}${path}`, init);
    if (!response.ok) {
      throw new Error(`cp-api ${method} ${path} -> ${response.status}`);
    }
    if (response.status === 204) return undefined as T;
    return (await response.json()) as T;
  };
}

/* Operation map */

export interface CpApiOperations {
  GetAgents: {
    method: "GET";
    path: "/agents";
    request: unknown;
    response: AgentList;
  };
  PostAgents: {
    method: "POST";
    path: "/agents";
    request: AgentCreate;
    response: Agent;
  };
  GetAgentsByAgentId: {
    method: "GET";
    path: "/agents/{agent_id}";
    request: unknown;
    response: Agent;
  };
  DeleteAgentsByAgentId: {
    method: "DELETE";
    path: "/agents/{agent_id}";
    request: unknown;
    response: unknown;
  };
  GetAgentsByAgentIdConductor: {
    method: "GET";
    path: "/agents/{agent_id}/conductor";
    request: unknown;
    response: ConductorData;
  };
  GetAgentsByAgentIdConversations: {
    method: "GET";
    path: "/agents/{agent_id}/conversations";
    request: unknown;
    response: { "items"?: Conversation[]; "next_cursor"?: string | null };
  };
  PostAgentsByAgentIdInvoke: {
    method: "POST";
    path: "/agents/{agent_id}/invoke";
    request: InvokeRequest;
    response: AgentResponse;
  };
  GetAgentsByAgentIdMemory: {
    method: "GET";
    path: "/agents/{agent_id}/memory";
    request: unknown;
    response: MemoryStudioEntryList;
  };
  DeleteAgentsByAgentIdMemoryUserByMemoryKey: {
    method: "DELETE";
    path: "/agents/{agent_id}/memory/user/{memory_key}";
    request: unknown;
    response: unknown;
  };
  GetAgentsByAgentIdTools: {
    method: "GET";
    path: "/agents/{agent_id}/tools";
    request: unknown;
    response: AgentToolList;
  };
  GetAgentsByAgentIdVersions: {
    method: "GET";
    path: "/agents/{agent_id}/versions";
    request: unknown;
    response: AgentVersionList;
  };
  PostAgentsByAgentIdVersions: {
    method: "POST";
    path: "/agents/{agent_id}/versions";
    request: AgentVersionCreate;
    response: AgentVersion;
  };
  PostAgentsByAgentIdVersionsByVersionIdPromote: {
    method: "POST";
    path: "/agents/{agent_id}/versions/{version_id}/promote";
    request: unknown;
    response: Agent;
  };
  GetAuditEventsLegacy: {
    method: "GET";
    path: "/audit-events";
    request: unknown;
    response: AuditEventList;
  };
  GetAuditEvents: {
    method: "GET";
    path: "/audit/events";
    request: unknown;
    response: AuditEventList;
  };
  PostAuthExchange: {
    method: "POST";
    path: "/auth/exchange";
    request: AuthExchangeRequest;
    response: AuthExchangeResponse;
  };
  GetBudgets: {
    method: "GET";
    path: "/budgets";
    request: unknown;
    response: Budget[];
  };
  PostBudgets: {
    method: "POST";
    path: "/budgets";
    request: { "hard_usd"?: number; "scope": "workspace" | "agent" | "conversation" | "day"; "scope_id"?: string | null; "soft_usd"?: number };
    response: Budget;
  };
  GetConversationsByConversationId: {
    method: "GET";
    path: "/conversations/{conversation_id}";
    request: unknown;
    response: ConversationDetail;
  };
  PostConversationsByConversationIdHandback: {
    method: "POST";
    path: "/conversations/{conversation_id}/handback";
    request: { "note": string };
    response: Conversation;
  };
  PostConversationsByConversationIdOperatorMessages: {
    method: "POST";
    path: "/conversations/{conversation_id}/operator-messages";
    request: OperatorMessageRequest;
    response: ConversationMessage;
  };
  PostConversationsByConversationIdTakeover: {
    method: "POST";
    path: "/conversations/{conversation_id}/takeover";
    request: { "note": string };
    response: Conversation;
  };
  GetEvalRunsByRunId: {
    method: "GET";
    path: "/eval-runs/{run_id}";
    request: unknown;
    response: EvalRunDetail;
  };
  PostEvalSuites: {
    method: "POST";
    path: "/eval-suites";
    request: { "cases"?: EvalCase[]; "name": string };
    response: EvalSuite;
  };
  GetEvalSuitesBySuiteIdCases: {
    method: "GET";
    path: "/eval-suites/{suite_id}/cases";
    request: unknown;
    response: EvalCaseList;
  };
  PostEvalSuitesBySuiteIdCases: {
    method: "POST";
    path: "/eval-suites/{suite_id}/cases";
    request: EvalCase;
    response: EvalCase;
  };
  PostEvalSuitesBySuiteIdRuns: {
    method: "POST";
    path: "/eval-suites/{suite_id}/runs";
    request: { "agent_version_id": string; "baseline_version_id"?: string };
    response: EvalRun;
  };
  GetHealthz: {
    method: "GET";
    path: "/healthz";
    request: unknown;
    response: unknown;
  };
  PostInboxByItemIdClaim: {
    method: "POST";
    path: "/inbox/{item_id}/claim";
    request: InboxClaimRequest;
    response: InboxItem;
  };
  PostInboxByItemIdRelease: {
    method: "POST";
    path: "/inbox/{item_id}/release";
    request: unknown;
    response: InboxItem;
  };
  PostInboxByItemIdResolve: {
    method: "POST";
    path: "/inbox/{item_id}/resolve";
    request: InboxResolveRequest;
    response: InboxItem;
  };
  PostKb: {
    method: "POST";
    path: "/kb";
    request: KBCreate;
    response: KB;
  };
  PostKbByKbIdIngest: {
    method: "POST";
    path: "/kb/{kb_id}/ingest";
    request: KBIngestUrl | KBIngestNotion | KBIngestS3;
    response: { "document_id"?: string; "status"?: string };
  };
  GetKbByKbIdSearch: {
    method: "GET";
    path: "/kb/{kb_id}/search";
    request: unknown;
    response: RetrievalChunk[];
  };
  GetMarketplace: {
    method: "GET";
    path: "/marketplace";
    request: unknown;
    response: MarketplaceBrowseList;
  };
  GetMcp: {
    method: "GET";
    path: "/mcp";
    request: unknown;
    response: MCPServer[];
  };
  PostMcp: {
    method: "POST";
    path: "/mcp";
    request: { "config"?: Record<string, unknown>; "source": string };
    response: MCPServer;
  };
  GetReadyz: {
    method: "GET";
    path: "/readyz";
    request: unknown;
    response: unknown;
  };
  GetTracesSearch: {
    method: "GET";
    path: "/traces/search";
    request: unknown;
    response: { "items"?: Trace[]; "next_cursor"?: string | null };
  };
  GetTracesByTurnId: {
    method: "GET";
    path: "/traces/{turn_id}";
    request: unknown;
    response: Trace;
  };
  PostTurns: {
    method: "POST";
    path: "/turns";
    request: RuntimeTurnRequest;
    response: RuntimeTurnResponse;
  };
  PostTurnsStream: {
    method: "POST";
    path: "/turns/stream";
    request: RuntimeTurnRequest;
    response: unknown;
  };
  GetUsage: {
    method: "GET";
    path: "/usage";
    request: unknown;
    response: UsageReport;
  };
  GetVersion: {
    method: "GET";
    path: "/version";
    request: unknown;
    response: Version;
  };
  PostWebhooksIncoming: {
    method: "POST";
    path: "/webhooks/incoming";
    request: { "events": string[]; "secret"?: string; "url": string };
    response: WebhookRegistration;
  };
  GetWorkspaces: {
    method: "GET";
    path: "/workspaces";
    request: unknown;
    response: WorkspaceList;
  };
  PostWorkspaces: {
    method: "POST";
    path: "/workspaces";
    request: WorkspaceCreate;
    response: Workspace;
  };
  GetWorkspacesByWorkspaceId: {
    method: "GET";
    path: "/workspaces/{workspace_id}";
    request: unknown;
    response: Workspace;
  };
  PatchWorkspacesByWorkspaceId: {
    method: "PATCH";
    path: "/workspaces/{workspace_id}";
    request: WorkspacePatch;
    response: Workspace;
  };
  GetWorkspacesByWorkspaceIdApiKeys: {
    method: "GET";
    path: "/workspaces/{workspace_id}/api-keys";
    request: unknown;
    response: APIKey[];
  };
  PostWorkspacesByWorkspaceIdApiKeys: {
    method: "POST";
    path: "/workspaces/{workspace_id}/api-keys";
    request: { "name": string; "scopes": string[] };
    response: APIKeyCreated;
  };
  GetWorkspacesByWorkspaceIdCobuilder: {
    method: "GET";
    path: "/workspaces/{workspace_id}/cobuilder";
    request: unknown;
    response: CoBuilderWorkspace;
  };
  PostWorkspacesByWorkspaceIdEvalCasesFromResolution: {
    method: "POST";
    path: "/workspaces/{workspace_id}/eval-cases/from-resolution";
    request: ResolutionEvalCaseRequest;
    response: ResolutionEvalCaseResponse;
  };
  GetWorkspacesByWorkspaceIdInbox: {
    method: "GET";
    path: "/workspaces/{workspace_id}/inbox";
    request: unknown;
    response: InboxItemList;
  };
  PostWorkspacesByWorkspaceIdInboxEscalate: {
    method: "POST";
    path: "/workspaces/{workspace_id}/inbox/escalate";
    request: InboxEscalateRequest;
    response: InboxItem;
  };
  GetWorkspacesByWorkspaceIdMembers: {
    method: "GET";
    path: "/workspaces/{workspace_id}/members";
    request: unknown;
    response: WorkspaceMember[];
  };
  PostWorkspacesByWorkspaceIdMembers: {
    method: "POST";
    path: "/workspaces/{workspace_id}/members";
    request: { "email": string; "role": "owner" | "admin" | "editor" | "operator" | "viewer" };
    response: WorkspaceMember;
  };
  GetWorkspacesByWorkspaceIdMigrationParity: {
    method: "GET";
    path: "/workspaces/{workspace_id}/migration/parity";
    request: unknown;
    response: MigrationParityWorkspace;
  };
  GetWorkspacesByWorkspaceIdSecrets: {
    method: "GET";
    path: "/workspaces/{workspace_id}/secrets";
    request: unknown;
    response: SecretRef[];
  };
  GetWorkspacesByWorkspaceIdVoiceConfig: {
    method: "GET";
    path: "/workspaces/{workspace_id}/voice/config";
    request: unknown;
    response: VoiceConfig;
  };
  PatchWorkspacesByWorkspaceIdVoiceConfig: {
    method: "PATCH";
    path: "/workspaces/{workspace_id}/voice/config";
    request: VoiceConfigPatch;
    response: VoiceConfig;
  };
  GetWorkspacesByWorkspaceIdVoiceStage: {
    method: "GET";
    path: "/workspaces/{workspace_id}/voice/stage";
    request: unknown;
    response: VoiceStageModel;
  };
}

/* Generated client */

export interface CpApi {
  GetAgents(args: { body: unknown }): Promise<AgentList>;
  PostAgents(args: { body: AgentCreate }): Promise<Agent>;
  GetAgentsByAgentId(args: { agent_id: string; body: unknown }): Promise<Agent>;
  DeleteAgentsByAgentId(args: { agent_id: string; body: unknown }): Promise<unknown>;
  GetAgentsByAgentIdConductor(args: { agent_id: string; body: unknown }): Promise<ConductorData>;
  GetAgentsByAgentIdConversations(args: { agent_id: string; body: unknown }): Promise<{ "items"?: Conversation[]; "next_cursor"?: string | null }>;
  PostAgentsByAgentIdInvoke(args: { agent_id: string; body: InvokeRequest }): Promise<AgentResponse>;
  GetAgentsByAgentIdMemory(args: { agent_id: string; body: unknown }): Promise<MemoryStudioEntryList>;
  DeleteAgentsByAgentIdMemoryUserByMemoryKey(args: { agent_id: string; memory_key: string; body: unknown }): Promise<unknown>;
  GetAgentsByAgentIdTools(args: { agent_id: string; body: unknown }): Promise<AgentToolList>;
  GetAgentsByAgentIdVersions(args: { agent_id: string; body: unknown }): Promise<AgentVersionList>;
  PostAgentsByAgentIdVersions(args: { agent_id: string; body: AgentVersionCreate }): Promise<AgentVersion>;
  PostAgentsByAgentIdVersionsByVersionIdPromote(args: { agent_id: string; version_id: string; body: unknown }): Promise<Agent>;
  GetAuditEventsLegacy(args: { body: unknown }): Promise<AuditEventList>;
  GetAuditEvents(args: { body: unknown }): Promise<AuditEventList>;
  PostAuthExchange(args: { body: AuthExchangeRequest }): Promise<AuthExchangeResponse>;
  GetBudgets(args: { body: unknown }): Promise<Budget[]>;
  PostBudgets(args: { body: { "hard_usd"?: number; "scope": "workspace" | "agent" | "conversation" | "day"; "scope_id"?: string | null; "soft_usd"?: number } }): Promise<Budget>;
  GetConversationsByConversationId(args: { conversation_id: string; body: unknown }): Promise<ConversationDetail>;
  PostConversationsByConversationIdHandback(args: { conversation_id: string; body: { "note": string } }): Promise<Conversation>;
  PostConversationsByConversationIdOperatorMessages(args: { conversation_id: string; body: OperatorMessageRequest }): Promise<ConversationMessage>;
  PostConversationsByConversationIdTakeover(args: { conversation_id: string; body: { "note": string } }): Promise<Conversation>;
  GetEvalRunsByRunId(args: { run_id: string; body: unknown }): Promise<EvalRunDetail>;
  PostEvalSuites(args: { body: { "cases"?: EvalCase[]; "name": string } }): Promise<EvalSuite>;
  GetEvalSuitesBySuiteIdCases(args: { suite_id: string; body: unknown }): Promise<EvalCaseList>;
  PostEvalSuitesBySuiteIdCases(args: { suite_id: string; body: EvalCase }): Promise<EvalCase>;
  PostEvalSuitesBySuiteIdRuns(args: { suite_id: string; body: { "agent_version_id": string; "baseline_version_id"?: string } }): Promise<EvalRun>;
  GetHealthz(args: { body: unknown }): Promise<unknown>;
  PostInboxByItemIdClaim(args: { item_id: string; body: InboxClaimRequest }): Promise<InboxItem>;
  PostInboxByItemIdRelease(args: { item_id: string; body: unknown }): Promise<InboxItem>;
  PostInboxByItemIdResolve(args: { item_id: string; body: InboxResolveRequest }): Promise<InboxItem>;
  PostKb(args: { body: KBCreate }): Promise<KB>;
  PostKbByKbIdIngest(args: { kb_id: string; body: KBIngestUrl | KBIngestNotion | KBIngestS3 }): Promise<{ "document_id"?: string; "status"?: string }>;
  GetKbByKbIdSearch(args: { kb_id: string; body: unknown }): Promise<RetrievalChunk[]>;
  GetMarketplace(args: { body: unknown }): Promise<MarketplaceBrowseList>;
  GetMcp(args: { body: unknown }): Promise<MCPServer[]>;
  PostMcp(args: { body: { "config"?: Record<string, unknown>; "source": string } }): Promise<MCPServer>;
  GetReadyz(args: { body: unknown }): Promise<unknown>;
  GetTracesSearch(args: { body: unknown }): Promise<{ "items"?: Trace[]; "next_cursor"?: string | null }>;
  GetTracesByTurnId(args: { turn_id: string; body: unknown }): Promise<Trace>;
  PostTurns(args: { body: RuntimeTurnRequest }): Promise<RuntimeTurnResponse>;
  PostTurnsStream(args: { body: RuntimeTurnRequest }): Promise<unknown>;
  GetUsage(args: { body: unknown }): Promise<UsageReport>;
  GetVersion(args: { body: unknown }): Promise<Version>;
  PostWebhooksIncoming(args: { body: { "events": string[]; "secret"?: string; "url": string } }): Promise<WebhookRegistration>;
  GetWorkspaces(args: { body: unknown }): Promise<WorkspaceList>;
  PostWorkspaces(args: { body: WorkspaceCreate }): Promise<Workspace>;
  GetWorkspacesByWorkspaceId(args: { workspace_id: string; body: unknown }): Promise<Workspace>;
  PatchWorkspacesByWorkspaceId(args: { workspace_id: string; body: WorkspacePatch }): Promise<Workspace>;
  GetWorkspacesByWorkspaceIdApiKeys(args: { workspace_id: string; body: unknown }): Promise<APIKey[]>;
  PostWorkspacesByWorkspaceIdApiKeys(args: { workspace_id: string; body: { "name": string; "scopes": string[] } }): Promise<APIKeyCreated>;
  GetWorkspacesByWorkspaceIdCobuilder(args: { workspace_id: string; body: unknown }): Promise<CoBuilderWorkspace>;
  PostWorkspacesByWorkspaceIdEvalCasesFromResolution(args: { workspace_id: string; body: ResolutionEvalCaseRequest }): Promise<ResolutionEvalCaseResponse>;
  GetWorkspacesByWorkspaceIdInbox(args: { workspace_id: string; body: unknown }): Promise<InboxItemList>;
  PostWorkspacesByWorkspaceIdInboxEscalate(args: { workspace_id: string; body: InboxEscalateRequest }): Promise<InboxItem>;
  GetWorkspacesByWorkspaceIdMembers(args: { workspace_id: string; body: unknown }): Promise<WorkspaceMember[]>;
  PostWorkspacesByWorkspaceIdMembers(args: { workspace_id: string; body: { "email": string; "role": "owner" | "admin" | "editor" | "operator" | "viewer" } }): Promise<WorkspaceMember>;
  GetWorkspacesByWorkspaceIdMigrationParity(args: { workspace_id: string; body: unknown }): Promise<MigrationParityWorkspace>;
  GetWorkspacesByWorkspaceIdSecrets(args: { workspace_id: string; body: unknown }): Promise<SecretRef[]>;
  GetWorkspacesByWorkspaceIdVoiceConfig(args: { workspace_id: string; body: unknown }): Promise<VoiceConfig>;
  PatchWorkspacesByWorkspaceIdVoiceConfig(args: { workspace_id: string; body: VoiceConfigPatch }): Promise<VoiceConfig>;
  GetWorkspacesByWorkspaceIdVoiceStage(args: { workspace_id: string; body: unknown }): Promise<VoiceStageModel>;
}

export function createCpApi(opts: CpApiClientOptions): CpApi {
  const fetcher = createCpApiFetch(opts);
  return {
    GetAgents: (args) => fetcher<AgentList>("GET", `/agents`, args.body),
    PostAgents: (args) => fetcher<Agent>("POST", `/agents`, args.body),
    GetAgentsByAgentId: (args) => fetcher<Agent>("GET", `/agents/${encodeURIComponent(args.agent_id)}`, args.body),
    DeleteAgentsByAgentId: (args) => fetcher<unknown>("DELETE", `/agents/${encodeURIComponent(args.agent_id)}`, args.body),
    GetAgentsByAgentIdConductor: (args) => fetcher<ConductorData>("GET", `/agents/${encodeURIComponent(args.agent_id)}/conductor`, args.body),
    GetAgentsByAgentIdConversations: (args) => fetcher<{ "items"?: Conversation[]; "next_cursor"?: string | null }>("GET", `/agents/${encodeURIComponent(args.agent_id)}/conversations`, args.body),
    PostAgentsByAgentIdInvoke: (args) => fetcher<AgentResponse>("POST", `/agents/${encodeURIComponent(args.agent_id)}/invoke`, args.body),
    GetAgentsByAgentIdMemory: (args) => fetcher<MemoryStudioEntryList>("GET", `/agents/${encodeURIComponent(args.agent_id)}/memory`, args.body),
    DeleteAgentsByAgentIdMemoryUserByMemoryKey: (args) => fetcher<unknown>("DELETE", `/agents/${encodeURIComponent(args.agent_id)}/memory/user/${encodeURIComponent(args.memory_key)}`, args.body),
    GetAgentsByAgentIdTools: (args) => fetcher<AgentToolList>("GET", `/agents/${encodeURIComponent(args.agent_id)}/tools`, args.body),
    GetAgentsByAgentIdVersions: (args) => fetcher<AgentVersionList>("GET", `/agents/${encodeURIComponent(args.agent_id)}/versions`, args.body),
    PostAgentsByAgentIdVersions: (args) => fetcher<AgentVersion>("POST", `/agents/${encodeURIComponent(args.agent_id)}/versions`, args.body),
    PostAgentsByAgentIdVersionsByVersionIdPromote: (args) => fetcher<Agent>("POST", `/agents/${encodeURIComponent(args.agent_id)}/versions/${encodeURIComponent(args.version_id)}/promote`, args.body),
    GetAuditEventsLegacy: (args) => fetcher<AuditEventList>("GET", `/audit-events`, args.body),
    GetAuditEvents: (args) => fetcher<AuditEventList>("GET", `/audit/events`, args.body),
    PostAuthExchange: (args) => fetcher<AuthExchangeResponse>("POST", `/auth/exchange`, args.body),
    GetBudgets: (args) => fetcher<Budget[]>("GET", `/budgets`, args.body),
    PostBudgets: (args) => fetcher<Budget>("POST", `/budgets`, args.body),
    GetConversationsByConversationId: (args) => fetcher<ConversationDetail>("GET", `/conversations/${encodeURIComponent(args.conversation_id)}`, args.body),
    PostConversationsByConversationIdHandback: (args) => fetcher<Conversation>("POST", `/conversations/${encodeURIComponent(args.conversation_id)}/handback`, args.body),
    PostConversationsByConversationIdOperatorMessages: (args) => fetcher<ConversationMessage>("POST", `/conversations/${encodeURIComponent(args.conversation_id)}/operator-messages`, args.body),
    PostConversationsByConversationIdTakeover: (args) => fetcher<Conversation>("POST", `/conversations/${encodeURIComponent(args.conversation_id)}/takeover`, args.body),
    GetEvalRunsByRunId: (args) => fetcher<EvalRunDetail>("GET", `/eval-runs/${encodeURIComponent(args.run_id)}`, args.body),
    PostEvalSuites: (args) => fetcher<EvalSuite>("POST", `/eval-suites`, args.body),
    GetEvalSuitesBySuiteIdCases: (args) => fetcher<EvalCaseList>("GET", `/eval-suites/${encodeURIComponent(args.suite_id)}/cases`, args.body),
    PostEvalSuitesBySuiteIdCases: (args) => fetcher<EvalCase>("POST", `/eval-suites/${encodeURIComponent(args.suite_id)}/cases`, args.body),
    PostEvalSuitesBySuiteIdRuns: (args) => fetcher<EvalRun>("POST", `/eval-suites/${encodeURIComponent(args.suite_id)}/runs`, args.body),
    GetHealthz: (args) => fetcher<unknown>("GET", `/healthz`, args.body),
    PostInboxByItemIdClaim: (args) => fetcher<InboxItem>("POST", `/inbox/${encodeURIComponent(args.item_id)}/claim`, args.body),
    PostInboxByItemIdRelease: (args) => fetcher<InboxItem>("POST", `/inbox/${encodeURIComponent(args.item_id)}/release`, args.body),
    PostInboxByItemIdResolve: (args) => fetcher<InboxItem>("POST", `/inbox/${encodeURIComponent(args.item_id)}/resolve`, args.body),
    PostKb: (args) => fetcher<KB>("POST", `/kb`, args.body),
    PostKbByKbIdIngest: (args) => fetcher<{ "document_id"?: string; "status"?: string }>("POST", `/kb/${encodeURIComponent(args.kb_id)}/ingest`, args.body),
    GetKbByKbIdSearch: (args) => fetcher<RetrievalChunk[]>("GET", `/kb/${encodeURIComponent(args.kb_id)}/search`, args.body),
    GetMarketplace: (args) => fetcher<MarketplaceBrowseList>("GET", `/marketplace`, args.body),
    GetMcp: (args) => fetcher<MCPServer[]>("GET", `/mcp`, args.body),
    PostMcp: (args) => fetcher<MCPServer>("POST", `/mcp`, args.body),
    GetReadyz: (args) => fetcher<unknown>("GET", `/readyz`, args.body),
    GetTracesSearch: (args) => fetcher<{ "items"?: Trace[]; "next_cursor"?: string | null }>("GET", `/traces/search`, args.body),
    GetTracesByTurnId: (args) => fetcher<Trace>("GET", `/traces/${encodeURIComponent(args.turn_id)}`, args.body),
    PostTurns: (args) => fetcher<RuntimeTurnResponse>("POST", `/turns`, args.body),
    PostTurnsStream: (args) => fetcher<unknown>("POST", `/turns/stream`, args.body),
    GetUsage: (args) => fetcher<UsageReport>("GET", `/usage`, args.body),
    GetVersion: (args) => fetcher<Version>("GET", `/version`, args.body),
    PostWebhooksIncoming: (args) => fetcher<WebhookRegistration>("POST", `/webhooks/incoming`, args.body),
    GetWorkspaces: (args) => fetcher<WorkspaceList>("GET", `/workspaces`, args.body),
    PostWorkspaces: (args) => fetcher<Workspace>("POST", `/workspaces`, args.body),
    GetWorkspacesByWorkspaceId: (args) => fetcher<Workspace>("GET", `/workspaces/${encodeURIComponent(args.workspace_id)}`, args.body),
    PatchWorkspacesByWorkspaceId: (args) => fetcher<Workspace>("PATCH", `/workspaces/${encodeURIComponent(args.workspace_id)}`, args.body),
    GetWorkspacesByWorkspaceIdApiKeys: (args) => fetcher<APIKey[]>("GET", `/workspaces/${encodeURIComponent(args.workspace_id)}/api-keys`, args.body),
    PostWorkspacesByWorkspaceIdApiKeys: (args) => fetcher<APIKeyCreated>("POST", `/workspaces/${encodeURIComponent(args.workspace_id)}/api-keys`, args.body),
    GetWorkspacesByWorkspaceIdCobuilder: (args) => fetcher<CoBuilderWorkspace>("GET", `/workspaces/${encodeURIComponent(args.workspace_id)}/cobuilder`, args.body),
    PostWorkspacesByWorkspaceIdEvalCasesFromResolution: (args) => fetcher<ResolutionEvalCaseResponse>("POST", `/workspaces/${encodeURIComponent(args.workspace_id)}/eval-cases/from-resolution`, args.body),
    GetWorkspacesByWorkspaceIdInbox: (args) => fetcher<InboxItemList>("GET", `/workspaces/${encodeURIComponent(args.workspace_id)}/inbox`, args.body),
    PostWorkspacesByWorkspaceIdInboxEscalate: (args) => fetcher<InboxItem>("POST", `/workspaces/${encodeURIComponent(args.workspace_id)}/inbox/escalate`, args.body),
    GetWorkspacesByWorkspaceIdMembers: (args) => fetcher<WorkspaceMember[]>("GET", `/workspaces/${encodeURIComponent(args.workspace_id)}/members`, args.body),
    PostWorkspacesByWorkspaceIdMembers: (args) => fetcher<WorkspaceMember>("POST", `/workspaces/${encodeURIComponent(args.workspace_id)}/members`, args.body),
    GetWorkspacesByWorkspaceIdMigrationParity: (args) => fetcher<MigrationParityWorkspace>("GET", `/workspaces/${encodeURIComponent(args.workspace_id)}/migration/parity`, args.body),
    GetWorkspacesByWorkspaceIdSecrets: (args) => fetcher<SecretRef[]>("GET", `/workspaces/${encodeURIComponent(args.workspace_id)}/secrets`, args.body),
    GetWorkspacesByWorkspaceIdVoiceConfig: (args) => fetcher<VoiceConfig>("GET", `/workspaces/${encodeURIComponent(args.workspace_id)}/voice/config`, args.body),
    PatchWorkspacesByWorkspaceIdVoiceConfig: (args) => fetcher<VoiceConfig>("PATCH", `/workspaces/${encodeURIComponent(args.workspace_id)}/voice/config`, args.body),
    GetWorkspacesByWorkspaceIdVoiceStage: (args) => fetcher<VoiceStageModel>("GET", `/workspaces/${encodeURIComponent(args.workspace_id)}/voice/stage`, args.body),
  };
}
