// AUTOGENERATED by tools/gen_cp_api_client.py from
// loop_implementation/api/openapi.yaml. Do not edit by hand.
// Run `pnpm --filter @loop/studio run gen:cp-api` to refresh.

/* Component schemas */

export interface APIKey {
  created_at?: string;
  id?: string;
  key_prefix?: string;
  last_used_at?: string | null;
  name?: string;
  revoked_at?: string | null;
  scopes?: string[];
}

export interface APIKeyCreated {
  id?: string;
  key?: string;
  name?: string;
  scopes?: string[];
}

export interface Agent {
  active_version?: number | null;
  created_at?: string;
  description?: string;
  id?: string;
  name?: string;
  slug?: string;
  workspace_id?: string;
}

export interface AgentCreate {
  description?: string;
  name: string;
  slug: string;
}

export interface AgentList {
  items: Agent[];
}

export interface AgentResponse {
  content?: ContentPart[];
  conversation_id?: string;
  end_turn?: boolean;
  suggested_actions?: Record<string, unknown>[];
}

export interface AgentVersion {
  agent_id?: string;
  deploy_state?: "inactive" | "canary" | "active" | "rolled_back";
  deployed_at?: string | null;
  eval_status?: "pending" | "running" | "passed" | "failed" | "skipped";
  id?: string;
  version?: number;
}

export interface AuditEvent {
  action?: string;
  actor_sub?: string;
  id?: string;
  occurred_at?: string;
  outcome?: "success" | "denied" | "error";
  payload_hash?: string | null;
  request_id?: string | null;
  resource_id?: string | null;
  resource_type?: string;
  workspace_id?: string;
}

export interface AuditEventList {
  items: AuditEvent[];
  total: number;
}

export interface AuditLogEntry {
  action?: string;
  actor_user_id?: string | null;
  after_state?: Record<string, unknown> | null;
  before_state?: Record<string, unknown> | null;
  client_ip?: string;
  created_at?: string;
  id?: string;
  request_id?: string;
  resource_id?: string | null;
  resource_type?: string;
  user_agent?: string | null;
}

export interface AuthExchangeRequest {
  id_token: string;
}

export interface AuthExchangeResponse {
  access_expires_at_ms: number;
  access_token: string;
  refresh_expires_at_ms: number;
  refresh_token: string;
  token_type: "Bearer";
}

export interface Budget {
  created_at?: string;
  hard_usd?: number | null;
  id?: string;
  remaining_usd?: number | null;
  scope?: "workspace" | "agent" | "conversation" | "day";
  scope_id?: string | null;
  soft_usd?: number | null;
  spent_usd?: number;
}

export interface ContentPart {
  bytes_b64?: string;
  mime_type?: string;
  text?: string;
  type: "text" | "image" | "audio" | "file";
  url?: string;
}

export interface Conversation {
  agent_id?: string;
  channel_type?: string;
  id?: string;
  last_at?: string;
  status?: "active" | "idle" | "closed" | "escalated";
  user_id?: string;
}

export type ConversationDetail = Conversation & { "turns"?: Turn[] };

export interface EvalCase {
  expected: Record<string, unknown>;
  input: Record<string, unknown>;
  name: string;
  scorers: { "config"?: Record<string, unknown>; "kind"?: "llm_judge" | "embedding_sim" | "regex_match" | "json_schema" | "tool_call_assert" | "latency_le" | "cost_le" | "hallucination" | "toxicity" | "pii_leak" }[];
}

export interface EvalRun {
  agent_version_id?: string;
  ended_at?: string | null;
  id?: string;
  started_at?: string;
  status?: string;
  suite_id?: string;
}

export type EvalRunDetail = EvalRun & { "results"?: { "case_name"?: string; "passed"?: boolean; "regressed"?: boolean; "score"?: number }[] };

export interface EvalSuite {
  case_count?: number;
  id?: string;
  name?: string;
}

export interface InvokeRequest {
  channel: "web" | "whatsapp" | "slack" | "teams" | "telegram" | "sms" | "email" | "discord" | "voice" | "webhook";
  content: ContentPart[];
  conversation_id: string;
  metadata?: Record<string, unknown>;
  user_id: string;
}

export interface KB {
  embedding_model?: string;
  id?: string;
  name?: string;
  vector_dim?: number;
}

export interface KBCreate {
  embedding_model?: string;
  name: string;
  vector_dim?: number;
}

export interface KBIngestNotion {
  integration_token: string;
  page_or_db: string;
  type: string;
}

export interface KBIngestS3 {
  s3_uri: string;
  type: string;
}

export interface KBIngestUrl {
  crawl?: boolean;
  type: string;
  url: string;
}

export interface MCPServer {
  id?: string;
  install_status?: "pending" | "installed" | "failed" | "disabled";
  manifest?: { "tools"?: { "description"?: string; "input_schema"?: Record<string, unknown>; "name"?: string }[] };
  name?: string;
  source_url?: string;
  version?: string;
}

export interface ProblemDetail {
  detail?: string;
  instance?: string;
  request_id?: string;
  status: number;
  title: string;
  type: string;
}

export type RegionName = "na-east" | "eu-west";

export interface RetrievalChunk {
  byte_range?: number[];
  chunk_id?: string;
  content?: string;
  doc_id?: string;
  score?: number;
  source_uri?: string;
}

export interface RuntimeTurnRequest {
  agent_name?: string;
  budget?: TurnBudget;
  channel?: "web" | "whatsapp" | "slack" | "teams" | "telegram" | "sms" | "email" | "discord" | "voice" | "webhook";
  content?: ContentPart[];
  conversation_id: string;
  input?: string | null;
  metadata?: Record<string, unknown>;
  model?: string | null;
  received_at?: string | null;
  request_id?: string | null;
  system_prompt?: string;
  user_id: string;
  workspace_id: string;
}

export interface RuntimeTurnResponse {
  events: TurnEvent[];
  reply: { "text": string };
  turn_id: string;
}

export interface SecretRef {
  agent_version_id?: string;
  created_at?: string;
  id?: string;
  rotated_at?: string | null;
  secret_name?: string;
}

export interface Trace {
  spans?: { "attrs"?: Record<string, unknown>; "cost_usd"?: number; "kind"?: "llm" | "tool" | "retrieval" | "memory" | "channel"; "latency_ms"?: number; "name"?: string; "parent_span_id"?: string | null; "span_id"?: string; "started_at"?: string; "status"?: string }[];
  turn_id?: string;
}

export interface Turn {
  content_json?: Record<string, unknown>;
  cost_usd?: number;
  ended_at?: string;
  id?: string;
  latency_ms?: number;
  role?: string;
  seq?: number;
  started_at?: string;
  token_in?: number;
  token_out?: number;
}

export interface TurnBudget {
  fallback_model?: string | null;
  max_cost_usd?: number;
  max_iterations?: number;
  max_output_tokens_per_iter?: number;
  max_runtime_seconds?: number;
}

export interface TurnEvent {
  payload: Record<string, unknown>;
  ts: string;
  type: "token" | "tool_call" | "tool_call_start" | "tool_call_end" | "tool_result" | "retrieval" | "trace" | "degrade" | "complete";
}

export interface UsageReport {
  from?: string;
  rows?: { "agent_seconds"?: number; "compute_usd"?: number; "date"?: string; "dim"?: string; "llm_input_tokens"?: number; "llm_output_tokens"?: number; "llm_usd"?: number; "tool_usd"?: number }[];
  to?: string;
}

export interface Version {
  api_version?: string;
  build_hash?: string;
  built_at?: string;
}

export interface WebhookRegistration {
  created_at?: string;
  events?: string[];
  id?: string;
  is_active?: boolean;
  last_triggered_at?: string | null;
  url?: string;
}

export interface Workspace {
  created_at?: string;
  id?: string;
  name?: string;
  plan?: "hobby" | "pro" | "team" | "enterprise";
  region?: RegionName;
  slug?: string;
}

export interface WorkspaceCreate {
  name: string;
  region?: RegionName;
  slug: string;
}

export interface WorkspaceList {
  items: Workspace[];
  page: number;
  page_size: number;
  total: number;
}

export interface WorkspaceMember {
  email?: string;
  full_name?: string;
  invited_at?: string;
  joined_at?: string | null;
  role?: "owner" | "admin" | "editor" | "operator" | "viewer";
  user_id?: string;
}

export interface WorkspacePatch {
  name?: string;
}


/**
 * Minimal fetch wrapper used by the generated cp-api client.
 *
 * Studio code rarely calls this directly; instead it imports
 * ``CpApi`` below and the wrapper handles URL templating, JSON
 * serialisation, and bearer auth.
 */
export interface CpApiClientOptions {
  baseUrl: string;
  token?: string;
  fetch?: typeof fetch;
}

export type CpApiFetch = <T>(
  method: string,
  path: string,
  body?: unknown,
) => Promise<T>;

export function createCpApiFetch(opts: CpApiClientOptions): CpApiFetch {
  const f = opts.fetch ?? fetch;
  const base = opts.baseUrl.replace(/\/$/, "");
  return async <T>(method: string, path: string, body?: unknown): Promise<T> => {
    const headers: Record<string, string> = { accept: "application/json" };
    if (opts.token) headers.authorization = `Bearer ${opts.token}`;
    const init: RequestInit = { method, headers };
    if (body !== undefined) {
      headers["content-type"] = "application/json";
      init.body = JSON.stringify(body);
    }
    const response = await f(`${base}${path}`, init);
    if (!response.ok) {
      throw new Error(`cp-api ${method} ${path} -> ${response.status}`);
    }
    if (response.status === 204) return undefined as T;
    return (await response.json()) as T;
  };
}

/* Operation map */

export interface CpApiOperations {
  GetAgents: {
    method: "GET";
    path: "/agents";
    request: unknown;
    response: AgentList;
  };
  PostAgents: {
    method: "POST";
    path: "/agents";
    request: AgentCreate;
    response: Agent;
  };
  GetAgentsByAgentId: {
    method: "GET";
    path: "/agents/{agent_id}";
    request: unknown;
    response: Agent;
  };
  DeleteAgentsByAgentId: {
    method: "DELETE";
    path: "/agents/{agent_id}";
    request: unknown;
    response: unknown;
  };
  GetAgentsByAgentIdConversations: {
    method: "GET";
    path: "/agents/{agent_id}/conversations";
    request: unknown;
    response: { "items"?: Conversation[]; "next_cursor"?: string | null };
  };
  PostAgentsByAgentIdInvoke: {
    method: "POST";
    path: "/agents/{agent_id}/invoke";
    request: InvokeRequest;
    response: AgentResponse;
  };
  PostAgentsByAgentIdVersions: {
    method: "POST";
    path: "/agents/{agent_id}/versions";
    request: unknown;
    response: AgentVersion;
  };
  GetAuditEvents: {
    method: "GET";
    path: "/audit-events";
    request: unknown;
    response: AuditEventList;
  };
  GetAuditEvents: {
    method: "GET";
    path: "/audit/events";
    request: unknown;
    response: AuditEventList;
  };
  PostAuthExchange: {
    method: "POST";
    path: "/auth/exchange";
    request: AuthExchangeRequest;
    response: AuthExchangeResponse;
  };
  GetBudgets: {
    method: "GET";
    path: "/budgets";
    request: unknown;
    response: Budget[];
  };
  PostBudgets: {
    method: "POST";
    path: "/budgets";
    request: { "hard_usd"?: number; "scope": "workspace" | "agent" | "conversation" | "day"; "scope_id"?: string | null; "soft_usd"?: number };
    response: Budget;
  };
  GetConversationsByConversationId: {
    method: "GET";
    path: "/conversations/{conversation_id}";
    request: unknown;
    response: ConversationDetail;
  };
  PostConversationsByConversationIdMessages: {
    method: "POST";
    path: "/conversations/{conversation_id}/messages";
    request: { "content": ContentPart[] };
    response: unknown;
  };
  PostConversationsByConversationIdTakeover: {
    method: "POST";
    path: "/conversations/{conversation_id}/takeover";
    request: { "reason": string };
    response: Conversation;
  };
  GetEvalRunsByRunId: {
    method: "GET";
    path: "/eval-runs/{run_id}";
    request: unknown;
    response: EvalRunDetail;
  };
  PostEvalSuites: {
    method: "POST";
    path: "/eval-suites";
    request: { "cases"?: EvalCase[]; "name": string };
    response: EvalSuite;
  };
  GetEvalSuitesBySuiteIdCases: {
    method: "GET";
    path: "/eval-suites/{suite_id}/cases";
    request: unknown;
    response: EvalCase[];
  };
  PostEvalSuitesBySuiteIdCases: {
    method: "POST";
    path: "/eval-suites/{suite_id}/cases";
    request: EvalCase;
    response: EvalCase;
  };
  DeleteEvalSuitesBySuiteIdCases: {
    method: "DELETE";
    path: "/eval-suites/{suite_id}/cases";
    request: unknown;
    response: unknown;
  };
  PostEvalSuitesBySuiteIdRuns: {
    method: "POST";
    path: "/eval-suites/{suite_id}/runs";
    request: { "agent_version_id": string; "baseline_version_id"?: string };
    response: EvalRun;
  };
  GetHealthz: {
    method: "GET";
    path: "/healthz";
    request: unknown;
    response: unknown;
  };
  PostKb: {
    method: "POST";
    path: "/kb";
    request: KBCreate;
    response: KB;
  };
  PostKbByKbIdIngest: {
    method: "POST";
    path: "/kb/{kb_id}/ingest";
    request: KBIngestUrl | KBIngestNotion | KBIngestS3;
    response: { "document_id"?: string; "status"?: string };
  };
  GetKbByKbIdSearch: {
    method: "GET";
    path: "/kb/{kb_id}/search";
    request: unknown;
    response: RetrievalChunk[];
  };
  GetMcp: {
    method: "GET";
    path: "/mcp";
    request: unknown;
    response: MCPServer[];
  };
  PostMcp: {
    method: "POST";
    path: "/mcp";
    request: { "config"?: Record<string, unknown>; "source": string };
    response: MCPServer;
  };
  GetReadyz: {
    method: "GET";
    path: "/readyz";
    request: unknown;
    response: unknown;
  };
  GetTracesSearch: {
    method: "GET";
    path: "/traces/search";
    request: unknown;
    response: { "items"?: Trace[]; "next_cursor"?: string | null };
  };
  GetTracesByTurnId: {
    method: "GET";
    path: "/traces/{turn_id}";
    request: unknown;
    response: Trace;
  };
  PostTurns: {
    method: "POST";
    path: "/turns";
    request: RuntimeTurnRequest;
    response: RuntimeTurnResponse;
  };
  PostTurnsStream: {
    method: "POST";
    path: "/turns/stream";
    request: RuntimeTurnRequest;
    response: unknown;
  };
  GetUsage: {
    method: "GET";
    path: "/usage";
    request: unknown;
    response: UsageReport;
  };
  GetVersion: {
    method: "GET";
    path: "/version";
    request: unknown;
    response: Version;
  };
  PostWebhooksIncoming: {
    method: "POST";
    path: "/webhooks/incoming";
    request: { "events": string[]; "secret"?: string; "url": string };
    response: WebhookRegistration;
  };
  GetWorkspaces: {
    method: "GET";
    path: "/workspaces";
    request: unknown;
    response: WorkspaceList;
  };
  PostWorkspaces: {
    method: "POST";
    path: "/workspaces";
    request: WorkspaceCreate;
    response: Workspace;
  };
  GetWorkspacesByWorkspaceId: {
    method: "GET";
    path: "/workspaces/{workspace_id}";
    request: unknown;
    response: Workspace;
  };
  PatchWorkspacesByWorkspaceId: {
    method: "PATCH";
    path: "/workspaces/{workspace_id}";
    request: WorkspacePatch;
    response: Workspace;
  };
  GetWorkspacesByWorkspaceIdApiKeys: {
    method: "GET";
    path: "/workspaces/{workspace_id}/api-keys";
    request: unknown;
    response: APIKey[];
  };
  PostWorkspacesByWorkspaceIdApiKeys: {
    method: "POST";
    path: "/workspaces/{workspace_id}/api-keys";
    request: { "name": string; "scopes": string[] };
    response: APIKeyCreated;
  };
  GetWorkspacesByWorkspaceIdMembers: {
    method: "GET";
    path: "/workspaces/{workspace_id}/members";
    request: unknown;
    response: WorkspaceMember[];
  };
  PostWorkspacesByWorkspaceIdMembers: {
    method: "POST";
    path: "/workspaces/{workspace_id}/members";
    request: { "email": string; "role": "owner" | "admin" | "editor" | "operator" | "viewer" };
    response: WorkspaceMember;
  };
  GetWorkspacesByWorkspaceIdSecrets: {
    method: "GET";
    path: "/workspaces/{workspace_id}/secrets";
    request: unknown;
    response: SecretRef[];
  };
}

/* Generated client */

export interface CpApi {
  GetAgents(args: { body: unknown }): Promise<AgentList>;
  PostAgents(args: { body: AgentCreate }): Promise<Agent>;
  GetAgentsByAgentId(args: { agent_id: string; body: unknown }): Promise<Agent>;
  DeleteAgentsByAgentId(args: { agent_id: string; body: unknown }): Promise<unknown>;
  GetAgentsByAgentIdConversations(args: { agent_id: string; body: unknown }): Promise<{ "items"?: Conversation[]; "next_cursor"?: string | null }>;
  PostAgentsByAgentIdInvoke(args: { agent_id: string; body: InvokeRequest }): Promise<AgentResponse>;
  PostAgentsByAgentIdVersions(args: { agent_id: string; body: unknown }): Promise<AgentVersion>;
  GetAuditEvents(args: { body: unknown }): Promise<AuditEventList>;
  GetAuditEvents(args: { body: unknown }): Promise<AuditEventList>;
  PostAuthExchange(args: { body: AuthExchangeRequest }): Promise<AuthExchangeResponse>;
  GetBudgets(args: { body: unknown }): Promise<Budget[]>;
  PostBudgets(args: { body: { "hard_usd"?: number; "scope": "workspace" | "agent" | "conversation" | "day"; "scope_id"?: string | null; "soft_usd"?: number } }): Promise<Budget>;
  GetConversationsByConversationId(args: { conversation_id: string; body: unknown }): Promise<ConversationDetail>;
  PostConversationsByConversationIdMessages(args: { conversation_id: string; body: { "content": ContentPart[] } }): Promise<unknown>;
  PostConversationsByConversationIdTakeover(args: { conversation_id: string; body: { "reason": string } }): Promise<Conversation>;
  GetEvalRunsByRunId(args: { run_id: string; body: unknown }): Promise<EvalRunDetail>;
  PostEvalSuites(args: { body: { "cases"?: EvalCase[]; "name": string } }): Promise<EvalSuite>;
  GetEvalSuitesBySuiteIdCases(args: { suite_id: string; body: unknown }): Promise<EvalCase[]>;
  PostEvalSuitesBySuiteIdCases(args: { suite_id: string; body: EvalCase }): Promise<EvalCase>;
  DeleteEvalSuitesBySuiteIdCases(args: { suite_id: string; body: unknown }): Promise<unknown>;
  PostEvalSuitesBySuiteIdRuns(args: { suite_id: string; body: { "agent_version_id": string; "baseline_version_id"?: string } }): Promise<EvalRun>;
  GetHealthz(args: { body: unknown }): Promise<unknown>;
  PostKb(args: { body: KBCreate }): Promise<KB>;
  PostKbByKbIdIngest(args: { kb_id: string; body: KBIngestUrl | KBIngestNotion | KBIngestS3 }): Promise<{ "document_id"?: string; "status"?: string }>;
  GetKbByKbIdSearch(args: { kb_id: string; body: unknown }): Promise<RetrievalChunk[]>;
  GetMcp(args: { body: unknown }): Promise<MCPServer[]>;
  PostMcp(args: { body: { "config"?: Record<string, unknown>; "source": string } }): Promise<MCPServer>;
  GetReadyz(args: { body: unknown }): Promise<unknown>;
  GetTracesSearch(args: { body: unknown }): Promise<{ "items"?: Trace[]; "next_cursor"?: string | null }>;
  GetTracesByTurnId(args: { turn_id: string; body: unknown }): Promise<Trace>;
  PostTurns(args: { body: RuntimeTurnRequest }): Promise<RuntimeTurnResponse>;
  PostTurnsStream(args: { body: RuntimeTurnRequest }): Promise<unknown>;
  GetUsage(args: { body: unknown }): Promise<UsageReport>;
  GetVersion(args: { body: unknown }): Promise<Version>;
  PostWebhooksIncoming(args: { body: { "events": string[]; "secret"?: string; "url": string } }): Promise<WebhookRegistration>;
  GetWorkspaces(args: { body: unknown }): Promise<WorkspaceList>;
  PostWorkspaces(args: { body: WorkspaceCreate }): Promise<Workspace>;
  GetWorkspacesByWorkspaceId(args: { workspace_id: string; body: unknown }): Promise<Workspace>;
  PatchWorkspacesByWorkspaceId(args: { workspace_id: string; body: WorkspacePatch }): Promise<Workspace>;
  GetWorkspacesByWorkspaceIdApiKeys(args: { workspace_id: string; body: unknown }): Promise<APIKey[]>;
  PostWorkspacesByWorkspaceIdApiKeys(args: { workspace_id: string; body: { "name": string; "scopes": string[] } }): Promise<APIKeyCreated>;
  GetWorkspacesByWorkspaceIdMembers(args: { workspace_id: string; body: unknown }): Promise<WorkspaceMember[]>;
  PostWorkspacesByWorkspaceIdMembers(args: { workspace_id: string; body: { "email": string; "role": "owner" | "admin" | "editor" | "operator" | "viewer" } }): Promise<WorkspaceMember>;
  GetWorkspacesByWorkspaceIdSecrets(args: { workspace_id: string; body: unknown }): Promise<SecretRef[]>;
}

export function createCpApi(opts: CpApiClientOptions): CpApi {
  const fetcher = createCpApiFetch(opts);
  return {
    GetAgents: (args) => fetcher<AgentList>("GET", `/agents`, args.body),
    PostAgents: (args) => fetcher<Agent>("POST", `/agents`, args.body),
    GetAgentsByAgentId: (args) => fetcher<Agent>("GET", `/agents/${encodeURIComponent(args.agent_id)}`, args.body),
    DeleteAgentsByAgentId: (args) => fetcher<unknown>("DELETE", `/agents/${encodeURIComponent(args.agent_id)}`, args.body),
    GetAgentsByAgentIdConversations: (args) => fetcher<{ "items"?: Conversation[]; "next_cursor"?: string | null }>("GET", `/agents/${encodeURIComponent(args.agent_id)}/conversations`, args.body),
    PostAgentsByAgentIdInvoke: (args) => fetcher<AgentResponse>("POST", `/agents/${encodeURIComponent(args.agent_id)}/invoke`, args.body),
    PostAgentsByAgentIdVersions: (args) => fetcher<AgentVersion>("POST", `/agents/${encodeURIComponent(args.agent_id)}/versions`, args.body),
    GetAuditEvents: (args) => fetcher<AuditEventList>("GET", `/audit-events`, args.body),
    GetAuditEvents: (args) => fetcher<AuditEventList>("GET", `/audit/events`, args.body),
    PostAuthExchange: (args) => fetcher<AuthExchangeResponse>("POST", `/auth/exchange`, args.body),
    GetBudgets: (args) => fetcher<Budget[]>("GET", `/budgets`, args.body),
    PostBudgets: (args) => fetcher<Budget>("POST", `/budgets`, args.body),
    GetConversationsByConversationId: (args) => fetcher<ConversationDetail>("GET", `/conversations/${encodeURIComponent(args.conversation_id)}`, args.body),
    PostConversationsByConversationIdMessages: (args) => fetcher<unknown>("POST", `/conversations/${encodeURIComponent(args.conversation_id)}/messages`, args.body),
    PostConversationsByConversationIdTakeover: (args) => fetcher<Conversation>("POST", `/conversations/${encodeURIComponent(args.conversation_id)}/takeover`, args.body),
    GetEvalRunsByRunId: (args) => fetcher<EvalRunDetail>("GET", `/eval-runs/${encodeURIComponent(args.run_id)}`, args.body),
    PostEvalSuites: (args) => fetcher<EvalSuite>("POST", `/eval-suites`, args.body),
    GetEvalSuitesBySuiteIdCases: (args) => fetcher<EvalCase[]>("GET", `/eval-suites/${encodeURIComponent(args.suite_id)}/cases`, args.body),
    PostEvalSuitesBySuiteIdCases: (args) => fetcher<EvalCase>("POST", `/eval-suites/${encodeURIComponent(args.suite_id)}/cases`, args.body),
    DeleteEvalSuitesBySuiteIdCases: (args) => fetcher<unknown>("DELETE", `/eval-suites/${encodeURIComponent(args.suite_id)}/cases`, args.body),
    PostEvalSuitesBySuiteIdRuns: (args) => fetcher<EvalRun>("POST", `/eval-suites/${encodeURIComponent(args.suite_id)}/runs`, args.body),
    GetHealthz: (args) => fetcher<unknown>("GET", `/healthz`, args.body),
    PostKb: (args) => fetcher<KB>("POST", `/kb`, args.body),
    PostKbByKbIdIngest: (args) => fetcher<{ "document_id"?: string; "status"?: string }>("POST", `/kb/${encodeURIComponent(args.kb_id)}/ingest`, args.body),
    GetKbByKbIdSearch: (args) => fetcher<RetrievalChunk[]>("GET", `/kb/${encodeURIComponent(args.kb_id)}/search`, args.body),
    GetMcp: (args) => fetcher<MCPServer[]>("GET", `/mcp`, args.body),
    PostMcp: (args) => fetcher<MCPServer>("POST", `/mcp`, args.body),
    GetReadyz: (args) => fetcher<unknown>("GET", `/readyz`, args.body),
    GetTracesSearch: (args) => fetcher<{ "items"?: Trace[]; "next_cursor"?: string | null }>("GET", `/traces/search`, args.body),
    GetTracesByTurnId: (args) => fetcher<Trace>("GET", `/traces/${encodeURIComponent(args.turn_id)}`, args.body),
    PostTurns: (args) => fetcher<RuntimeTurnResponse>("POST", `/turns`, args.body),
    PostTurnsStream: (args) => fetcher<unknown>("POST", `/turns/stream`, args.body),
    GetUsage: (args) => fetcher<UsageReport>("GET", `/usage`, args.body),
    GetVersion: (args) => fetcher<Version>("GET", `/version`, args.body),
    PostWebhooksIncoming: (args) => fetcher<WebhookRegistration>("POST", `/webhooks/incoming`, args.body),
    GetWorkspaces: (args) => fetcher<WorkspaceList>("GET", `/workspaces`, args.body),
    PostWorkspaces: (args) => fetcher<Workspace>("POST", `/workspaces`, args.body),
    GetWorkspacesByWorkspaceId: (args) => fetcher<Workspace>("GET", `/workspaces/${encodeURIComponent(args.workspace_id)}`, args.body),
    PatchWorkspacesByWorkspaceId: (args) => fetcher<Workspace>("PATCH", `/workspaces/${encodeURIComponent(args.workspace_id)}`, args.body),
    GetWorkspacesByWorkspaceIdApiKeys: (args) => fetcher<APIKey[]>("GET", `/workspaces/${encodeURIComponent(args.workspace_id)}/api-keys`, args.body),
    PostWorkspacesByWorkspaceIdApiKeys: (args) => fetcher<APIKeyCreated>("POST", `/workspaces/${encodeURIComponent(args.workspace_id)}/api-keys`, args.body),
    GetWorkspacesByWorkspaceIdMembers: (args) => fetcher<WorkspaceMember[]>("GET", `/workspaces/${encodeURIComponent(args.workspace_id)}/members`, args.body),
    PostWorkspacesByWorkspaceIdMembers: (args) => fetcher<WorkspaceMember>("POST", `/workspaces/${encodeURIComponent(args.workspace_id)}/members`, args.body),
    GetWorkspacesByWorkspaceIdSecrets: (args) => fetcher<SecretRef[]>("GET", `/workspaces/${encodeURIComponent(args.workspace_id)}/secrets`, args.body),
  };
}
