import type { ObservatoryModel } from "@/lib/observatory";

export const OBSERVATORY_MODEL: ObservatoryModel = {
  metrics: [
    {
      id: "quality",
      label: "Quality",
      value: "96.4%",
      delta: "+1.8 from baseline",
      tone: "healthy",
      nextAction: "Keep the refund replay suite pinned to deploy preflight.",
    },
    {
      id: "latency",
      label: "P95 latency",
      value: "1.18 s",
      delta: "-180 ms under draft",
      tone: "watching",
      nextAction:
        "Batch entitlement lookup with order lookup to save another 90 ms.",
    },
    {
      id: "cost",
      label: "Cost per turn",
      value: "$0.043",
      delta: "-7% against v23.1.4",
      tone: "healthy",
      nextAction: "Cache low-risk policy context on repeat refund turns.",
    },
    {
      id: "knowledge",
      label: "Citation health",
      value: "91%",
      delta: "6 metadata gaps",
      tone: "drifting",
      nextAction: "Open Inverse Retrieval for the region metadata cluster.",
    },
    {
      id: "handoff",
      label: "Escalation rate",
      value: "4.2%",
      delta: "+0.6 after draft",
      tone: "watching",
      nextAction: "Review legal-threat scenes before canary reaches 25%.",
    },
    {
      id: "deploy",
      label: "Deploy state",
      value: "12% canary",
      delta: "1 approval missing",
      tone: "watching",
      nextAction:
        "Ask Trust Review to approve the Spanish refund regression fix.",
    },
  ],
  anomalies: [
    {
      id: "anom_legal_synonym",
      title: "Attorney synonym misses legal handoff rule",
      severity: "high",
      evidence:
        "17 production-like variants failed in replay and persona simulation.",
      affectedObject: "behavior/escalation_classifier",
      nextAction:
        "Patch the escalation classifier, then replay the affected scene.",
      owner: "CX Policy",
      traceQuery: "trace_legal_synonym OR scene:legal-threat",
      taskRef: "task/legal-synonym-classifier",
    },
    {
      id: "anom_region_metadata",
      title: "Region metadata absent on renewal chunks",
      severity: "medium",
      evidence: "6 missed retrievals should have cited refund_policy_2026.pdf.",
      affectedObject: "knowledge/refund_policy_2026.pdf",
      nextAction: "Backfill region metadata and regenerate retrieval evals.",
      owner: "Knowledge Lead",
      traceQuery: "retrieval:zero-result source:refund_policy_2026.pdf",
      evalCandidateRef: "eval/retrieval/region-metadata",
    },
    {
      id: "anom_tool_wait",
      title: "Tool wait exceeds voice budget",
      severity: "medium",
      evidence: "lookup_order adds 180 ms where the voice budget is 160 ms.",
      affectedObject: "tool/lookup_order",
      nextAction: "Use preview batching before enabling phone canary.",
      owner: "Platform Integrations",
      traceQuery: "tool:lookup_order duration_ms:>160 channel:voice",
    },
  ],
  incidents: [
    {
      id: "inc_rollback_schema",
      workspace_id: "workspace_fixture",
      agent_id: "agent_support",
      deployment_id: "dep_v24",
      severity: "high",
      trigger: "error_rate breached 4% for web_chat canary",
      status: "contained",
      affected_trace_ids: ["trace_refund_742", "trace_legal_synonym"],
      affected_conversation_count: 17,
      root_cause_hypothesis: "Tool schema changed upstream during canary.",
      rollback_action_ref: "deployment/dep_v24/rollback",
      proposed_fix:
        "Pin the tool schema, replay affected traces, and create a Change Package with regression coverage.",
      candidate_eval_suite_id: null,
      fix_change_package_id: null,
      channel_scope: ["web_chat"],
      notifications: [
        {
          recipient: "maya@acme.test",
          channel: "in_app",
          status: "queued",
          sent_at: "2026-05-09T03:12:00.000Z",
          summary: "high incident: error_rate breached 4% for web_chat canary",
        },
        {
          recipient: "diego@acme.test",
          channel: "in_app",
          status: "queued",
          sent_at: "2026-05-09T03:12:00.000Z",
          summary: "high incident: error_rate breached 4% for web_chat canary",
        },
      ],
      timeline: [
        {
          kind: "incident_created",
          at: "2026-05-09T03:12:00.000Z",
          summary: "Incident created from auto_rollback.",
        },
        {
          kind: "containment",
          at: "2026-05-09T03:12:38.000Z",
          summary: "Auto-rollback moved traffic away from v24.",
        },
      ],
      report: {
        rollback_status: "executed",
        suspected_cause: "Tool schema changed upstream during canary.",
        proposed_fix:
          "Pin the tool schema, replay affected traces, and create a Change Package with regression coverage.",
      },
      created_at: "2026-05-09T03:12:00.000Z",
      created_by: "loop-system",
      resolved_at: null,
    },
  ],
  tail: [
    {
      id: "tail_1",
      time: "12:04:22",
      channel: "Web",
      summary: "Refund refusal cited policy and created handoff.",
      traceId: "trace_refund_742",
      status: "healthy",
    },
    {
      id: "tail_2",
      time: "12:05:10",
      channel: "Voice",
      summary: "Caller interrupted TTS; barge-in preserved renewal context.",
      traceId: "trace_voice_119",
      status: "watching",
    },
    {
      id: "tail_3",
      time: "12:06:03",
      channel: "Slack",
      summary: "Attorney wording skipped legal handoff under draft replay.",
      traceId: "trace_legal_synonym",
      status: "drifting",
    },
    {
      id: "tail_4",
      time: "12:06:44",
      channel: "WhatsApp",
      summary: "Spanish paraphrase passed citation and handoff eval.",
      traceId: "trace_spanish_pass",
      status: "healthy",
    },
  ],
  agents: [
    {
      id: "agent_support",
      name: "Support concierge",
      evalPassRate: 96,
      p95LatencyMs: 1180,
      costDeltaPct: -7,
      escalationRate: 4.2,
      tone: "healthy",
    },
    {
      id: "agent_sales",
      name: "Sales concierge",
      evalPassRate: 88,
      p95LatencyMs: 1640,
      costDeltaPct: 4,
      escalationRate: 7.8,
      tone: "watching",
    },
  ],
  recommendation: {
    title: "Next best operating action",
    body: "Patch the escalation classifier, then replay the affected scene.",
    observed:
      "17 production-like variants failed in replay and persona simulation.",
    intended:
      "Bring behavior/escalation_classifier back inside its committed behavior before expanding production exposure.",
    source: "observatory/anomaly/anom_legal_synonym",
    confidence: 86,
    confidenceLevel: "medium",
    tone: "warning",
  },
};
