#!/usr/bin/env python3
"""Generate the studio cp-api client (S152).

This generator reuses the schema/operation rendering from
``tools.gen_openapi_ts`` and writes a narrow, fetch-based client at
``apps/studio/src/lib/cp-api/generated.ts``. The studio invokes this
indirectly via ``pnpm run gen:cp-api`` so that the cp-api types stay in
lock-step with ``loop_implementation/api/openapi.yaml``.

Surface:
  * Component schema types (re-exported as ``Schemas``-prefixed nothing,
    just the bare interface names).
  * A ``CpApi`` object: one method per operation.
  * A reusable ``CpApiFetch`` callable so studio code can swap in a
    custom fetch (test doubles, retries, etc).
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

import yaml

from gen_openapi_ts import (  # type: ignore[import-not-found]
    OPENAPI_PATH,
    _operation_name,
    _render_schema,
    _request_type,
    _response_type,
)

REPO_ROOT = Path(__file__).resolve().parent.parent
OUT_PATH = (
    REPO_ROOT / "apps" / "studio" / "src" / "lib" / "cp-api" / "generated.ts"
)

HEADER = (
    "// AUTOGENERATED by tools/gen_cp_api_client.py from\n"
    "// loop_implementation/api/openapi.yaml. Do not edit by hand.\n"
    "// Run `pnpm --filter @loop/studio run gen:cp-api` to refresh.\n"
)

CLIENT_PRELUDE = """
/**
 * Minimal fetch wrapper used by the generated cp-api client.
 *
 * Studio code rarely calls this directly; instead it imports
 * ``CpApi`` below and the wrapper handles URL templating, JSON
 * serialisation, and bearer auth.
 */
export interface CpApiClientOptions {
  baseUrl: string;
  token?: string;
  fetch?: typeof fetch;
}

export type CpApiFetch = <T>(
  method: string,
  path: string,
  body?: unknown,
) => Promise<T>;

export function createCpApiFetch(opts: CpApiClientOptions): CpApiFetch {
  const f = opts.fetch ?? fetch;
  const base = opts.baseUrl.replace(/\\/$/, "");
  return async <T>(method: string, path: string, body?: unknown): Promise<T> => {
    const headers: Record<string, string> = { accept: "application/json" };
    if (opts.token) headers.authorization = `Bearer ${opts.token}`;
    const init: RequestInit = { method, headers };
    if (body !== undefined) {
      headers["content-type"] = "application/json";
      init.body = JSON.stringify(body);
    }
    const response = await f(`${base}${path}`, init);
    if (!response.ok) {
      throw new Error(`cp-api ${method} ${path} -> ${response.status}`);
    }
    if (response.status === 204) return undefined as T;
    return (await response.json()) as T;
  };
}
"""


def _expand_path(path: str) -> str:
    """Convert `/foo/{id}` template into a JS template literal."""

    return path.replace("{", "${encodeURIComponent(args.").replace("}", ")}")


def render_ts() -> str:
    data = yaml.safe_load(OPENAPI_PATH.read_text(encoding="utf-8"))
    if not isinstance(data, dict):
        raise ValueError("openapi document must be a mapping")

    schemas = data.get("components", {}).get("schemas", {})
    if not isinstance(schemas, dict):
        schemas = {}

    blocks: list[str] = [HEADER, "/* Component schemas */\n"]
    for name in sorted(schemas):
        blocks.append(_render_schema(name, schemas[name]))

    blocks.append(CLIENT_PRELUDE)
    blocks.append("/* Operation map */\n")
    blocks.append("export interface CpApiOperations {")

    operations: list[tuple[str, str, str, str, str, list[str]]] = []
    paths = data.get("paths", {})
    component_params = data.get("components", {}).get("parameters", {})
    if not isinstance(component_params, dict):
        component_params = {}

    def _resolve_param(p: object) -> dict[str, object] | None:
        if not isinstance(p, dict):
            return None
        ref = p.get("$ref")
        if isinstance(ref, str) and ref.startswith("#/components/parameters/"):
            target = component_params.get(ref.removeprefix("#/components/parameters/"))
            if isinstance(target, dict):
                return target
            return None
        return p

    if isinstance(paths, dict):
        for path in sorted(paths):
            methods = paths[path]
            if not isinstance(methods, dict):
                continue
            path_level_params = methods.get("parameters") or []
            for method in ("get", "post", "patch", "put", "delete"):
                operation = methods.get(method)
                if not isinstance(operation, dict):
                    continue
                op_name = _operation_name(method, path, operation)
                request_t = _request_type(operation)
                response_t = _response_type(operation)
                merged: list[object] = []
                if isinstance(path_level_params, list):
                    merged.extend(path_level_params)
                op_params = operation.get("parameters") or []
                if isinstance(op_params, list):
                    merged.extend(op_params)
                path_params: list[str] = []
                seen: set[str] = set()
                for raw in merged:
                    resolved = _resolve_param(raw)
                    if resolved is None:
                        continue
                    if resolved.get("in") != "path":
                        continue
                    name = resolved.get("name")
                    if isinstance(name, str) and name not in seen:
                        path_params.append(name)
                        seen.add(name)
                operations.append(
                    (op_name, method, path, request_t, response_t, path_params)
                )
                blocks.append(f"  {op_name}: {{")
                blocks.append(f'    method: "{method.upper()}";')
                blocks.append(f'    path: "{path}";')
                blocks.append(f"    request: {request_t};")
                blocks.append(f"    response: {response_t};")
                blocks.append("  };")
    blocks.append("}\n")

    blocks.append("/* Generated client */\n")
    blocks.append("export interface CpApi {")
    for op_name, _method, _path, request_t, response_t, params in operations:
        arg_bits: list[str] = []
        for name in params:
            arg_bits.append(f"{name}: string")
        if request_t != "never":
            arg_bits.append(f"body: {request_t}")
        signature = "()" if not arg_bits else f"(args: {{ {'; '.join(arg_bits)} }})"
        blocks.append(f"  {op_name}{signature}: Promise<{response_t}>;")
    blocks.append("}\n")

    blocks.append("export function createCpApi(opts: CpApiClientOptions): CpApi {")
    blocks.append("  const fetcher = createCpApiFetch(opts);")
    blocks.append("  return {")
    for op_name, method, path, request_t, response_t, params in operations:
        has_args = bool(params) or request_t != "never"
        if not has_args:
            blocks.append(
                f'    {op_name}: () => fetcher<{response_t}>("{method.upper()}", "{path}"),'
            )
            continue
        url = _expand_path(path)
        body_arg = "args.body" if request_t != "never" else "undefined"
        blocks.append(
            f"    {op_name}: (args) => fetcher<{response_t}>("
            f'"{method.upper()}", `{url}`, {body_arg}),'
        )
    blocks.append("  };")
    blocks.append("}\n")

    return "\n".join(blocks)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args(argv)
    rendered = render_ts()
    existing = OUT_PATH.read_text(encoding="utf-8") if OUT_PATH.exists() else None
    if args.check:
        if existing != rendered:
            print("error: cp-api client is out of sync", file=sys.stderr)
            return 1
        print("gen_cp_api_client: in sync.")
        return 0
    OUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    OUT_PATH.write_text(rendered, encoding="utf-8")
    print(f"gen_cp_api_client: wrote {OUT_PATH.relative_to(REPO_ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
