#!/usr/bin/env python3
"""Generate narrow TypeScript OpenAPI declarations for the Studio SDK.

The strategic TS SDK story needs a client surface that is generated from
``loop_implementation/api/openapi.yaml`` rather than hand-written request
shapes. This generator intentionally emits declarations only: runtime client
code lives in ``apps/studio/src/lib/loop-client.ts``.
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path

import yaml

REPO_ROOT = Path(__file__).resolve().parent.parent
OPENAPI_PATH = REPO_ROOT / "loop_implementation" / "api" / "openapi.yaml"
TS_OUT_PATH = REPO_ROOT / "apps" / "studio" / "src" / "lib" / "openapi-types.ts"

HEADER = (
    "// AUTOGENERATED by tools/gen_openapi_ts.py from loop_implementation/api/openapi.yaml.\n"
    "// Do not edit by hand. Run `uv run python tools/gen_openapi_ts.py` to refresh.\n"
)


def _pascal(name: str) -> str:
    parts = re.split(r"[^A-Za-z0-9]+", name)
    return "".join(p[:1].upper() + p[1:] for p in parts if p)


def _literal(value: object) -> str:
    if isinstance(value, str):
        return json.dumps(value)
    if isinstance(value, bool):
        return "true" if value else "false"
    if value is None:
        return "null"
    return str(value)


def _ref_name(ref: str) -> str:
    prefix = "#/components/schemas/"
    if not ref.startswith(prefix):
        return "unknown"
    return ref.removeprefix(prefix)


def _schema_type(schema: object) -> str:
    if not isinstance(schema, dict):
        return "unknown"
    if "$ref" in schema:
        return _ref_name(str(schema["$ref"]))
    if "enum" in schema and isinstance(schema["enum"], list):
        return " | ".join(_literal(v) for v in schema["enum"])
    if "oneOf" in schema and isinstance(schema["oneOf"], list):
        return " | ".join(_schema_type(s) for s in schema["oneOf"])
    if "anyOf" in schema and isinstance(schema["anyOf"], list):
        return " | ".join(_schema_type(s) for s in schema["anyOf"])
    if "allOf" in schema and isinstance(schema["allOf"], list):
        return " & ".join(_schema_type(s) for s in schema["allOf"])

    typ = schema.get("type")
    nullable = bool(schema.get("nullable"))
    if typ == "string":
        rendered = "string"
    elif typ in {"integer", "number"}:
        rendered = "number"
    elif typ == "boolean":
        rendered = "boolean"
    elif typ == "array":
        rendered = f"{_schema_type(schema.get('items', {}))}[]"
    elif typ == "object":
        props = schema.get("properties")
        additional = schema.get("additionalProperties")
        if isinstance(props, dict):
            rendered = _inline_object(props, schema.get("required", []))
        elif isinstance(additional, dict):
            rendered = f"Record<string, {_schema_type(additional)}>"
        else:
            rendered = "Record<string, unknown>"
    else:
        rendered = "unknown"
    return f"{rendered} | null" if nullable else rendered


def _inline_object(properties: dict[str, object], required_raw: object) -> str:
    required = set(required_raw if isinstance(required_raw, list) else [])
    bits: list[str] = []
    for key in sorted(properties):
        suffix = "" if key in required else "?"
        bits.append(f"{json.dumps(key)}{suffix}: {_schema_type(properties[key])}")
    return "{ " + "; ".join(bits) + " }"


def _render_schema(name: str, schema: object) -> str:
    if not isinstance(schema, dict):
        return f"export type {name} = unknown;\n"
    if schema.get("type") == "object" or "properties" in schema:
        props = schema.get("properties", {})
        required = set(schema.get("required", []) if isinstance(schema.get("required"), list) else [])
        if not isinstance(props, dict):
            return f"export type {name} = Record<string, unknown>;\n"
        lines = [f"export interface {name} {{"]
        for key in sorted(props):
            suffix = "" if key in required else "?"
            lines.append(f"  {key}{suffix}: {_schema_type(props[key])};")
        lines.append("}\n")
        return "\n".join(lines)
    return f"export type {name} = {_schema_type(schema)};\n"


def _response_type(operation: dict[str, object]) -> str:
    responses = operation.get("responses", {})
    if not isinstance(responses, dict):
        return "unknown"
    response = responses.get("200") or responses.get("201") or responses.get("202") or {}
    if not isinstance(response, dict):
        return "unknown"
    content = response.get("content", {})
    if not isinstance(content, dict):
        return "void"
    json_content = content.get("application/json", {})
    if not isinstance(json_content, dict):
        return "void"
    return _schema_type(json_content.get("schema", {}))


def _request_type(operation: dict[str, object]) -> str:
    body = operation.get("requestBody", {})
    if not isinstance(body, dict):
        return "never"
    content = body.get("content", {})
    if not isinstance(content, dict):
        return "never"
    json_content = content.get("application/json", {})
    if not isinstance(json_content, dict):
        return "never"
    return _schema_type(json_content.get("schema", {}))


def _operation_name(method: str, path: str, operation: dict[str, object]) -> str:
    raw = operation.get("operationId")
    if isinstance(raw, str) and raw:
        return _pascal(raw)
    clean = path.strip("/").replace("{", "by-").replace("}", "")
    return _pascal(f"{method}-{clean or 'root'}")


def render_ts() -> str:
    data = yaml.safe_load(OPENAPI_PATH.read_text(encoding="utf-8"))
    if not isinstance(data, dict):
        raise ValueError("openapi document must be a mapping")

    schemas = data.get("components", {}).get("schemas", {})
    if not isinstance(schemas, dict):
        schemas = {}
    blocks = [HEADER, "/* Component schemas */\n"]
    for name in sorted(schemas):
        blocks.append(_render_schema(name, schemas[name]))

    blocks.append("/* Operation map */\n")
    blocks.append("export interface Operations {")
    paths = data.get("paths", {})
    if isinstance(paths, dict):
        for path in sorted(paths):
            methods = paths[path]
            if not isinstance(methods, dict):
                continue
            for method in ("get", "post", "patch", "put", "delete"):
                operation = methods.get(method)
                if not isinstance(operation, dict):
                    continue
                op_name = _operation_name(method, path, operation)
                blocks.append(f"  {op_name}: {{")
                blocks.append(f"    method: {json.dumps(method.upper())};")
                blocks.append(f"    path: {json.dumps(path)};")
                blocks.append(f"    request: {_request_type(operation)};")
                blocks.append(f"    response: {_response_type(operation)};")
                blocks.append("  };")
    blocks.append("}\n")
    return "\n".join(blocks)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args(argv)
    rendered = render_ts()
    existing = TS_OUT_PATH.read_text(encoding="utf-8") if TS_OUT_PATH.exists() else None
    if args.check:
        if existing != rendered:
            print("error: OpenAPI TS declarations are out of sync", file=sys.stderr)
            return 1
        print("gen_openapi_ts: declarations are in sync.")
        return 0
    TS_OUT_PATH.write_text(rendered, encoding="utf-8")
    print(f"gen_openapi_ts: wrote {TS_OUT_PATH.relative_to(REPO_ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
