#!/usr/bin/env python3
"""Generate the TypeScript SDK type-declarations from the Python SDK.

Single source of truth: ``packages/sdk-py/loop/types.py``. Every
public pydantic model + StrEnum exposed in that module's ``__all__``
is rendered as a TypeScript ``interface`` (or string-union for the
StrEnums) into ``apps/studio/src/lib/sdk-types.ts``.

Usage (from repo root)::

    uv run python tools/gen_ts_sdk.py            # write
    uv run python tools/gen_ts_sdk.py --check    # CI: assert in sync

Type mapping (Python -> TypeScript)::

    str                 -> string
    int / float         -> number
    bool                -> boolean
    datetime / UUID     -> string
    Literal["a","b"]    -> "a" | "b"
    list[T]             -> T[]
    dict[str, V]        -> Record<string, V>
    T | None            -> T | null
    StrEnum             -> TS string union (one type alias per enum)
    Any                 -> unknown
    nested BaseModel    -> referenced TS interface name
"""

from __future__ import annotations

import argparse
import enum
import inspect
import sys
import types
from datetime import datetime
from pathlib import Path
from typing import Any, Literal, Union, get_args, get_origin
from uuid import UUID

REPO_ROOT = Path(__file__).resolve().parent.parent
SDK_PY_PATH = REPO_ROOT / "packages" / "sdk-py" / "loop" / "types.py"
TS_OUT_PATH = REPO_ROOT / "apps" / "studio" / "src" / "lib" / "sdk-types.ts"

HEADER = (
    "// AUTOGENERATED by tools/gen_ts_sdk.py from packages/sdk-py/loop/types.py.\n"
    "// Do not edit by hand. Run `uv run python tools/gen_ts_sdk.py` to refresh.\n"
)


def _is_optional(annotation: object) -> tuple[bool, object]:
    """Return ``(True, inner)`` if ``annotation`` is ``T | None``."""
    origin = get_origin(annotation)
    if origin is Union or origin is types.UnionType:
        args = [a for a in get_args(annotation) if a is not type(None)]
        if len(args) < len(get_args(annotation)):
            if len(args) == 1:
                return True, args[0]
            # Reduce to a Union of remaining members.
            return True, Union[tuple(args)]  # type: ignore[return-value]  # noqa: UP007
    return False, annotation


def _render_type(annotation: object) -> str:
    optional, inner = _is_optional(annotation)
    rendered = _render_non_optional(inner)
    return f"{rendered} | null" if optional else rendered


def _render_non_optional(annotation: object) -> str:
    if annotation is inspect.Parameter.empty or annotation is None:
        return "unknown"
    if annotation is Any:
        return "unknown"
    if annotation is str or annotation is UUID or annotation is datetime:
        return "string"
    if annotation is bool:
        return "boolean"
    if annotation is int or annotation is float:
        return "number"

    origin = get_origin(annotation)
    if origin is Literal:
        parts = [_render_literal_value(v) for v in get_args(annotation)]
        return " | ".join(parts)
    if origin is list:
        (inner,) = get_args(annotation) or (Any,)
        return f"{_render_type(inner)}[]"
    if origin is tuple:
        args = get_args(annotation)
        if len(args) == 2 and args[1] is Ellipsis:
            return f"{_render_type(args[0])}[]"
        return "[" + ", ".join(_render_type(a) for a in args) + "]"
    if origin is dict:
        args = get_args(annotation)
        if len(args) == 2:
            return f"Record<string, {_render_type(args[1])}>"
        return "Record<string, unknown>"
    if origin is Union or origin is types.UnionType:
        return " | ".join(_render_type(a) for a in get_args(annotation))

    if inspect.isclass(annotation):
        if issubclass(annotation, enum.Enum):
            return annotation.__name__
        # Assume any other class ref is a sibling pydantic model.
        return annotation.__name__

    return "unknown"


def _render_literal_value(value: object) -> str:
    if isinstance(value, str):
        escaped = value.replace("\\", "\\\\").replace('"', '\\"')
        return f'"{escaped}"'
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, (int, float)):
        return repr(value)
    if value is None:
        return "null"
    return f'"{value!s}"'


def _enum_block(name: str, members: list[str]) -> str:
    union = " | ".join(f'"{m}"' for m in members)
    return f"export type {name} = {union};\n"


def _pydantic_block(name: str, fields: list[tuple[str, str, bool]]) -> str:
    lines = [f"export interface {name} {{"]
    for field_name, ts_type, optional in fields:
        suffix = "?" if optional else ""
        lines.append(f"  {field_name}{suffix}: {ts_type};")
    lines.append("}\n")
    return "\n".join(lines)


def _collect_public_symbols(module: Any) -> list[Any]:
    """Yield symbols from ``module.__all__`` in declaration order."""
    names: list[str] = list(module.__all__)
    out: list[Any] = []
    for name in names:
        sym = getattr(module, name, None)
        if sym is None:
            continue
        out.append(sym)
    return out


def _import_sdk_types() -> Any:
    """Import the SDK types module without polluting sys.path globally."""
    sys.path.insert(0, str(SDK_PY_PATH.parent.parent))
    try:
        import loop.types as types_module  # type: ignore[import-not-found]

        return types_module
    finally:
        # Leave sys.path alone for callers; we *want* the import cached.
        pass


def render_ts() -> str:
    types_module = _import_sdk_types()
    from pydantic import BaseModel

    blocks: list[str] = []
    for sym in _collect_public_symbols(types_module):
        if inspect.isclass(sym) and issubclass(sym, enum.Enum):
            members = [m.value for m in sym]
            blocks.append(_enum_block(sym.__name__, members))
        elif inspect.isclass(sym) and issubclass(sym, BaseModel):
            fields: list[tuple[str, str, bool]] = []
            for field_name, field in sym.model_fields.items():
                annotation = field.annotation
                ts_type = _render_type(annotation)
                # A field is "optional" in TS-emit terms when it has a default.
                has_default = field.is_required() is False
                optional = has_default
                fields.append((field_name, ts_type, optional))
            blocks.append(_pydantic_block(sym.__name__, fields))
    return HEADER + "\n" + "\n".join(blocks)


def _read_existing() -> str | None:
    if not TS_OUT_PATH.exists():
        return None
    return TS_OUT_PATH.read_text(encoding="utf-8")


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="exit non-zero if the committed file disagrees with the generator",
    )
    args = parser.parse_args(argv)

    rendered = render_ts()
    existing = _read_existing()

    if args.check:
        if existing is None:
            print(f"error: {TS_OUT_PATH} does not exist", file=sys.stderr)
            return 1
        if existing != rendered:
            print(
                "error: TS SDK out of sync with packages/sdk-py/loop/types.py.\n"
                "       Run `uv run python tools/gen_ts_sdk.py` to refresh.",
                file=sys.stderr,
            )
            return 1
        print("gen_ts_sdk: TS SDK is in sync with the Python source of truth.")
        return 0

    TS_OUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    TS_OUT_PATH.write_text(rendered, encoding="utf-8")
    try:
        display = TS_OUT_PATH.relative_to(REPO_ROOT)
    except ValueError:
        display = TS_OUT_PATH
    print(f"gen_ts_sdk: wrote {display}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
